/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-20 05:59:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import hospital.model.vo.HospDoctor;
import member.model.service.MemberService;
import member.model.vo.User;
import hospital.model.vo.Hospital;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1595158624000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1595220082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("member.model.vo.User");
    _jspx_imports_classes.add("hospital.model.vo.Hospital");
    _jspx_imports_classes.add("hospital.model.vo.HospDoctor");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	Cookie[] cookies2 = request.getCookies();
	boolean saveUserIdChecked = false;
	String saveUserIdValue = "";
	if(cookies2 != null) {
		for(Cookie c : cookies2) {
			String k = c.getName();
			String v = c.getValue();

			if("saveUserId".equals(k)) {
				saveUserIdChecked = true;
				saveUserIdValue = v;
			}
		}
	}
	
	
	
	Hospital hospLoggedIn = (Hospital)session.getAttribute("hospLoggedIn");
	//쿠키관련
	Cookie[] cookies = request.getCookies();
	boolean saveHospIdChecked = false;
	String saveHospIdValue = "";
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();

			if("saveHospId".equals(k)) {
				saveHospIdChecked = true;
				saveHospIdValue = v;
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>See Doctor</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/footer.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top-bar\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <ul>\r\n");
      out.write("                ");
if(hospLoggedIn == null && userLoggedIn == null) { 
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("                        <li style=\"color:white\">홈</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/login\">\r\n");
      out.write("                        <li>로그인</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/register\">\r\n");
      out.write("                        <li>회원가입</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else if(hospLoggedIn != null) { 
      out.write("\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"><span class=\"login1\"><strong>");
      out.print( hospLoggedIn.getHospName() );
      out.write("</strong></span></a>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/edit-info?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>병원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/doctorList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>의사보기</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingHopitalList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역(병원)</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                 ");
}else if(userLoggedIn!=null&&userLoggedIn.getUserRole().equals(MemberService.MEMBER_ROLE_ADMIN)){ 
      out.write("   \r\n");
      out.write("                    <span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">\r\n");
      out.write("                        <li>회원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/hospList\">\r\n");
      out.write("                        <li>병원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                \t<span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit-info?userId=");
      out.print( userLoggedIn.getUserId());
      out.write("\">\r\n");
      out.write("                        <li>회원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookinglist?userId=");
      out.print( userLoggedIn.getUserId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sub-bar\"></div>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("\tvar cnt = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".seoul-lt\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchAddr\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\taddr1: \"서대문구\",\r\n");
      out.write("\t\t\t\taddr2: \"마포구\",\r\n");
      out.write("\t\t\t\taddr3: \"용산구\",\r\n");
      out.write("\t\t\t\taddr4: \"중구\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".seoul-lb\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchAddr\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\taddr1: \"양천구\",\r\n");
      out.write("\t\t\t\taddr2: \"관악구\",\r\n");
      out.write("\t\t\t\taddr3: \"구로구\",\r\n");
      out.write("\t\t\t\taddr4: \"금천구\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".seoul-rt\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchAddr\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\taddr1: \"도봉구\",\r\n");
      out.write("\t\t\t\taddr2: \"중랑구\",\r\n");
      out.write("\t\t\t\taddr3: \"성북구\",\r\n");
      out.write("\t\t\t\taddr4: \"성동구\",\r\n");
      out.write("\t\t\t\taddr5: \"광진구\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".seoul-mb\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchAddr\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\taddr1: \"강남구\",\r\n");
      out.write("\t\t\t\taddr2: \"서초구\",\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".seoul-rb\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchAddr\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\taddr1: \"강동구\",\r\n");
      out.write("\t\t\t\taddr2: \"송파구\",\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//진료과목별 검색\r\n");
      out.write("\t$(\".work-mid li:first-child\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchButton\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\thospDept: \"내과\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tconsole.log(cnt);\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".work-mid li:nth-child(2)\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchButton\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\thospDept: \"외과\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".work-mid li:nth-child(3)\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchButton\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\thospDept: \"안과\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".work-mid li:nth-child(4)\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchButton\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\thospDept: \"치과\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".work-mid li:nth-child(5)\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchButton\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\thospDept: \"피부과\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".work-mid li:nth-child(6)\").click(function() {\r\n");
      out.write("\t\tcnt = 0;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchButton\",\r\n");
      out.write("\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\thospDept: \"정신과\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".work-bot\");\r\n");
      out.write("\t\t\t\tif(res == null || res.length==0) {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"<li class='no-search'>조회된 병원이 없습니다.</li>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpaging(cnt);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("function searchHosp() {\r\n");
      out.write("\tlet $hospName = $(\"#hospName\");\r\n");
      out.write("\tlet $doctorName = $(\"#doctorName\");\r\n");
      out.write("\tlet $hospDept = $(\"#hospDept\");\r\n");
      out.write("\tcnt = 0;\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/searchButton\",\r\n");
      out.write("\t\tmethod: \"GET\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tdata: {\r\n");
      out.write("\t\t\thospName: $hospName.val(),\r\n");
      out.write("\t\t\tdoctorName: $doctorName.val(),\r\n");
      out.write("\t\t\thospDept: $hospDept.val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\tsuccess: function(res) {\r\n");
      out.write("\t\t\tif(res == null) {\r\n");
      out.write("\t\t\t\tconsole.log(\"조회된 병원이 없습니다.\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tlet $ul = $(\".s-result\");\r\n");
      out.write("\t\t\t\t$ul.html(\"\");\r\n");
      out.write("\t\t\t\tfor(let i in res) {\r\n");
      out.write("\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\tlet hosp = res[i];\r\n");
      out.write("\t\t\t\t\t//사진있을때\r\n");
      out.write("\t\t\t\t\tif(hosp.hospInfo!=null)\r\n");
      out.write("\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='upload/hospital/\"+hosp.hospInfo+\"' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t\t//사진없을때\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t$ul.append(\"<a class='work-card' href='");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=\"+hosp.hospId+\"'><li><img src='img/hos.jpg' alt=''><div class='s-info'><p class='hos-title'>\"+hosp.hospName+\"</p><p>\"+hosp.hospAddr+\"</p></div></li></a>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmainPaging(cnt);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#mybooking_main\").click(function () {\r\n");
      out.write("\t\r\n");
      out.write("\t   \t");
if(userLoggedIn != null) { 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tlet $userId = \"");
      out.print( userLoggedIn!=null? userLoggedIn.getUserId():"" );
      out.write("\";\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: \"");
      out.print( request.getContextPath() );
      out.write("/booking/bookingListMain\",\r\n");
      out.write("\t\t\t\t\tmethod: \"GET\",\r\n");
      out.write("\t\t\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\t\tuserId: $userId,\r\n");
      out.write("\t\t\t\t\t\tstate: \"A\",\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\t\t");
 if(userLoggedIn != null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#profile-tap\").html(data);\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#profile-tap\").children().html(\"<h1 style='text-align:center'>예약조회</h1><h4 style='text-align: center; margin-top:150px;'>로그인이 필요한 페이지입니다.</h4>\");\r\n");
      out.write("\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(xhr, status, err) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(xhr, status, err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t   \t");
 } 
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("    <section>\r\n");
      out.write("        <article>\r\n");
      out.write("            <ul class=\"work-btn\">\r\n");
      out.write("                <style>\r\n");
      out.write("                    li svg {\r\n");
      out.write("                        width: 100px;\r\n");
      out.write("                        height: 100px;\r\n");
      out.write("                        margin: 45px auto 10px;\r\n");
      out.write("                        display: block;\r\n");
      out.write("                    }\r\n");
      out.write("                </style>\r\n");
      out.write("                <li id=\"mybooking_main\">\r\n");
      out.write("                    <svg xmlns:x=\"http://ns.adobe.com/Extensibility/1.0/\"\r\n");
      out.write("                        xmlns:i=\"http://ns.adobe.com/AdobeIllustrator/10.0/\"\r\n");
      out.write("                        xmlns:graph=\"http://ns.adobe.com/Graphs/1.0/\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                        xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" x=\"0px\" y=\"0px\" viewBox=\"0 0 100 125\"\r\n");
      out.write("                        fill=\"white\" style=\"enable-background:new 0 0 100 100;\" xml:space=\"preserve\">\r\n");
      out.write("                        <switch>\r\n");
      out.write("                            <foreignObject requiredExtensions=\"http://ns.adobe.com/AdobeIllustrator/10.0/\" x=\"0\" y=\"0\"\r\n");
      out.write("                                width=\"1\" height=\"1\" />\r\n");
      out.write("                            <g i:extraneous=\"self\">\r\n");
      out.write("                                <g>\r\n");
      out.write("                                    <path d=\"M5273.1,2400.1v-2c0-2.8-5-4-9.7-4s-9.7,1.3-9.7,4v2c0,1.8,0.7,3.6,2,4.9l5,4.9c0.3,0.3,0.4,0.6,0.4,1v6.4     c0,0.4,0.2,0.7,0.6,0.8l2.9,0.9c0.5,0.1,1-0.2,1-0.8v-7.2c0-0.4,0.2-0.7,0.4-1l5.1-5C5272.4,2403.7,5273.1,2401.9,5273.1,2400.1z      M5263.4,2400c-4.8,0-7.4-1.3-7.5-1.8v0c0.1-0.5,2.7-1.8,7.5-1.8c4.8,0,7.3,1.3,7.5,1.8C5270.7,2398.7,5268.2,2400,5263.4,2400z\" />\r\n");
      out.write("                                    <path d=\"M5268.4,2410.3c-0.6,0-1,0.4-1,1c0,0.6,0.4,1,1,1h4.3c0.6,0,1-0.4,1-1c0-0.6-0.4-1-1-1H5268.4z\" />\r\n");
      out.write("                                    <path d=\"M5272.7,2413.7h-4.3c-0.6,0-1,0.4-1,1c0,0.6,0.4,1,1,1h4.3c0.6,0,1-0.4,1-1C5273.7,2414.1,5273.3,2413.7,5272.7,2413.7z\" />\r\n");
      out.write("                                    <path d=\"M5272.7,2417h-4.3c-0.6,0-1,0.4-1,1c0,0.6,0.4,1,1,1h4.3c0.6,0,1-0.4,1-1C5273.7,2417.5,5273.3,2417,5272.7,2417z\" />\r\n");
      out.write("                                </g>\r\n");
      out.write("                                <g>\r\n");
      out.write("                                    <path d=\"M83.6,8.8H70.9V5.2c0-1.5-1.2-2.7-2.7-2.7c-1.5,0-2.7,1.2-2.7,2.7v3.6H52.7V5.2c0-1.5-1.2-2.7-2.7-2.7     c-1.5,0-2.7,1.2-2.7,2.7v3.6H34.5V5.2c0-1.5-1.2-2.7-2.7-2.7c-1.5,0-2.7,1.2-2.7,2.7v3.6H16.4c-2.4,0-4.4,2-4.4,4.4v79.9     c0,2.4,2,4.4,4.4,4.4h67.2c2.4,0,4.4-2,4.4-4.4V13.2C88,10.8,86,8.8,83.6,8.8z M82.6,92.1H17.4V14.2h11.7v3.6     c0,1.5,1.2,2.7,2.7,2.7c1.5,0,2.7-1.2,2.7-2.7v-3.6h12.8v3.6c0,1.5,1.2,2.7,2.7,2.7c1.5,0,2.7-1.2,2.7-2.7v-3.6h12.8v3.6     c0,1.5,1.2,2.7,2.7,2.7c1.5,0,2.7-1.2,2.7-2.7v-3.6h11.7V92.1z\" />\r\n");
      out.write("                                    <path d=\"M30,42.3c0.5,0.6,1.2,0.9,2,0.9c0.8,0,1.5-0.3,2-0.9l6.2-6.7c1-1.1,1-2.8-0.1-3.8c-1.1-1-2.8-1-3.8,0.1L32,36.5l-1.3-1.4     C29.7,34,28,34,26.9,35c-1.1,1-1.2,2.7-0.1,3.8L30,42.3z\" />\r\n");
      out.write("                                    <path d=\"M36.2,50.6L32,55.1l-1.3-1.4c-1-1.1-2.7-1.2-3.8-0.1c-1.1,1-1.2,2.7-0.1,3.8L30,61c0.5,0.6,1.2,0.9,2,0.9     c0.8,0,1.5-0.3,2-0.9l6.2-6.7c1-1.1,1-2.8-0.1-3.8C39,49.5,37.2,49.5,36.2,50.6z\" />\r\n");
      out.write("                                    <path d=\"M36.2,69.3L32,73.8l-1.3-1.4c-1-1.1-2.7-1.2-3.8-0.1c-1.1,1-1.2,2.7-0.1,3.8l3.3,3.5c0.5,0.6,1.2,0.9,2,0.9     c0.8,0,1.5-0.3,2-0.9l6.2-6.7c1-1.1,1-2.8-0.1-3.8C39,68.1,37.2,68.2,36.2,69.3z\" />\r\n");
      out.write("                                    <path d=\"M71.2,53.1H47.7c-1.5,0-2.7,1.2-2.7,2.7c0,1.5,1.2,2.7,2.7,2.7h23.6c1.5,0,2.7-1.2,2.7-2.7     C73.9,54.3,72.7,53.1,71.2,53.1z\" />\r\n");
      out.write("                                    <path d=\"M47.7,34.4c-1.5,0-2.7,1.2-2.7,2.7c0,1.5,1.2,2.7,2.7,2.7h23.6c1.5,0,2.7-1.2,2.7-2.7c0-1.5-1.2-2.7-2.7-2.7H47.7z\" />\r\n");
      out.write("                                    <path d=\"M71.2,71.8H47.7c-1.5,0-2.7,1.2-2.7,2.7s1.2,2.7,2.7,2.7h23.6c1.5,0,2.7-1.2,2.7-2.7S72.7,71.8,71.2,71.8z\" />\r\n");
      out.write("                                </g>\r\n");
      out.write("                            </g>\r\n");
      out.write("                        </switch>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    예약조회\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 80\" x=\"0px\" y=\"0px\" fill=\"white\">\r\n");
      out.write("                        <g data-name=\"16\">\r\n");
      out.write("                            <path\r\n");
      out.write("                                d=\"M53.3,51.89a11.52,11.52,0,1,0-1.41,1.41l6.4,6.41a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42ZM44.5,54A9.5,9.5,0,1,1,54,44.5,9.51,9.51,0,0,1,44.5,54Z\" />\r\n");
      out.write("                            <path\r\n");
      out.write("                                d=\"M59,23H41V5a1,1,0,0,0-1-1H24a1,1,0,0,0-1,1V23H5a1,1,0,0,0-1,1V40a1,1,0,0,0,1,1H23V59a1,1,0,0,0,1,1H40a1,1,0,0,0,1-1v-.43A14.5,14.5,0,1,1,58.57,41H59a1,1,0,0,0,1-1V24A1,1,0,0,0,59,23Z\" />\r\n");
      out.write("                        </g>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    검색\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"");
      out.print(request.getContextPath());
      out.write("/healthBoard/healthboardList\" style=\"display: block; padding: 1px 0px 36px 0px; color:white;\"  fill=\"white\">\r\n");
      out.write("                 <svg version=\"1.0\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("\t\t\t\t\t width=\"1280.000000pt\" height=\"1280.000000pt\" viewBox=\"0 0 1280.000000 1280.000000\"\r\n");
      out.write("\t\t\t\t\t preserveAspectRatio=\"xMidYMid meet\">\r\n");
      out.write("\t\t\t\t\t<metadata>\r\n");
      out.write("\t\t\t\t\t</metadata>\r\n");
      out.write("\t\t\t\t\t<g transform=\"translate(0.000000,1280.000000) scale(0.100000,-0.100000)\"\r\n");
      out.write("\t\t\t\t\tfill=\"#ffffff\" stroke=\"none\">\r\n");
      out.write("\t\t\t\t\t<path d=\"M1820 12779 c-285 -30 -596 -134 -838 -282 -542 -331 -894 -887 -962\r\n");
      out.write("\t\t\t\t\t-1519 -14 -135 -14 -9021 0 -9156 52 -480 262 -911 606 -1242 338 -326 758\r\n");
      out.write("\t\t\t\t\t-518 1224 -560 91 -8 1367 -10 4645 -8 4277 3 4525 4 4615 21 234 44 406 100\r\n");
      out.write("\t\t\t\t\t595 194 531 266 908 739 1058 1331 l32 127 0 4715 0 4715 -32 127 c-96 380\r\n");
      out.write("\t\t\t\t\t-268 684 -537 954 -307 306 -657 485 -1116 571 -90 17 -335 18 -4650 19 -2549\r\n");
      out.write("\t\t\t\t\t1 -4592 -2 -4640 -7z m4655 -1379 c494 -35 945 -133 1355 -293 146 -57 433\r\n");
      out.write("\t\t\t\t\t-202 567 -285 586 -366 940 -837 1103 -1469 76 -291 111 -671 90 -983 -32\r\n");
      out.write("\t\t\t\t\t-498 -149 -869 -385 -1225 -200 -302 -474 -561 -1185 -1118 -211 -166 -423\r\n");
      out.write("\t\t\t\t\t-340 -470 -387 -181 -179 -307 -388 -366 -608 -28 -104 -54 -314 -66 -529\r\n");
      out.write("\t\t\t\t\tl-11 -213 -915 0 -915 0 7 168 c28 687 118 1228 245 1479 102 204 335 471 626\r\n");
      out.write("\t\t\t\t\t722 66 57 278 225 470 374 193 150 394 315 449 367 170 164 310 372 385 570\r\n");
      out.write("\t\t\t\t\t59 158 72 231 78 435 4 151 2 199 -15 300 -26 152 -68 280 -137 420 -191 390\r\n");
      out.write("\t\t\t\t\t-416 552 -880 631 -157 27 -533 25 -685 -4 -318 -60 -553 -194 -713 -405 -158\r\n");
      out.write("\t\t\t\t\t-208 -296 -520 -346 -780 -18 -91 -41 -287 -41 -350 0 -16 -51 -17 -962 -15\r\n");
      out.write("\t\t\t\t\tl-963 3 2 85 c4 122 21 304 44 460 154 1030 613 1765 1382 2215 417 243 905\r\n");
      out.write("\t\t\t\t\t388 1465 434 142 12 625 12 787 1z m775 -9005 l0 -965 -1005 0 -1005 0 0 965\r\n");
      out.write("\t\t\t\t\t0 965 1005 0 1005 0 0 -965z\"/>\r\n");
      out.write("\t\t\t\t\t</g>\r\n");
      out.write("\t\t\t\t</svg>\r\n");
      out.write("                   게시판\r\n");
      out.write("                 </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"work-wrap\">\r\n");
      out.write("                <div class=\"work-tap tap\">\r\n");
      out.write("                \t<ul class=\"search-btn\">\r\n");
      out.write("                \t\t<li style=\"background-color: #4286f4\">검색어</li>\r\n");
      out.write("                \t\t<li>지도</li>\r\n");
      out.write("                \t\t<li>진료과</li>\r\n");
      out.write("                \t</ul>\r\n");
      out.write("                \t<div class=\"search-wrap s-tap\">\r\n");
      out.write("                        <div class=\"search\">\r\n");
      out.write("                            <img src=\"img/s-round.png\" alt=\"\">\r\n");
      out.write("                            <input type=\"text\" id=\"hospName\" name=\"hospName\" placeholder=\"병원이름\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"search\">\r\n");
      out.write("                            <img src=\"img/s-round.png\" alt=\"\">\r\n");
      out.write("                            <input type=\"text\" id=\"doctorName\" name=\"doctorName\" placeholder=\"의사\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"search\">\r\n");
      out.write("                            <img src=\"img/s-round.png\" alt=\"\">\r\n");
      out.write("                            <input type=\"text\" id=\"hospDept\" name=\"hospDept\" placeholder=\"진료\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"button\" value=\"검색\" onclick=\"searchHosp();\" >\r\n");
      out.write("                    \t<ul class=\"s-result\">\r\n");
      out.write("\t                    \t<form action=\"\" id=\"s-SetRows\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"s-RowPerPage\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("                    \t</ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"work-top work s-tap\" style=\"display:none;\">\r\n");
      out.write("                        <div class=\"seoul\">\r\n");
      out.write("                            <p class=\"work-title\"><span>●</span>지역선택</p>\r\n");
      out.write("                            <div class=\"map\"></div>\r\n");
      out.write("                            <div class=\"seoul-lt\"></div>\r\n");
      out.write("                            <div class=\"seoul-lb\"></div>\r\n");
      out.write("                            <div class=\"seoul-rt\"></div>\r\n");
      out.write("                            <div class=\"seoul-mb\"></div>\r\n");
      out.write("                            <div class=\"seoul-rb\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"work-mid s-tap\" style=\"display:none;\">\r\n");
      out.write("                        <li>내과</li>\r\n");
      out.write("                        <li>외과</li>\r\n");
      out.write("                        <li>안과</li>\r\n");
      out.write("                        <li>치과</li>\r\n");
      out.write("                        <li>피부과</li>\r\n");
      out.write("                        <li>정신과</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"work-bot s-tap\" style=\"display:none;\">\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"profile-tap tap\" id=\"profile-tap\" style=\"display: none;\">\r\n");
      out.write("                    <div class=\"profile-wrap\">\r\n");
      out.write("                ");
 if( userLoggedIn != null) {
      out.write("\r\n");
      out.write("                        <div class=\"profile\">\r\n");
      out.write("                          \r\n");
      out.write("                        <ul class=\"res-result\">\r\n");
      out.write("                         \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    <div class=\"res-wrap\">\r\n");
      out.write("                        <h1><span>●</span> 내 예약 </h1>\r\n");
      out.write("                        <h3>로그인후 이용해주세요.</h3>\r\n");
      out.write("                \t</div>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                \t<div class=\"profile-wrap\">\r\n");
      out.write("                \t\t<div class=\"profile\">\r\n");
      out.write("                            <img src=\"img/person1.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul class=\"res-result\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"img/mypage-1.png\" alt=\"\">\r\n");
      out.write("                                <p>전체</p>\r\n");
      out.write("                                <h1>0</h1>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"img/mypage-2.png\" alt=\"\">\r\n");
      out.write("                                <p>이용예정</p>\r\n");
      out.write("                                <h1>0</h1>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"img/mypage-3.png\" alt=\"\">\r\n");
      out.write("                                <p>이용완료</p>\r\n");
      out.write("                                <h1>0</h1>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"img/mypage-4.png\" alt=\"\">\r\n");
      out.write("                                <p>취소</p>\r\n");
      out.write("                                <h1>0</h1>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"res-wrap\">\r\n");
      out.write("                \t\t<h1 style=\"margin-top: 200px; text-align:center;\">예약 내역을 확인하기위해 로그인을 해주세요.</h1>\r\n");
      out.write("                \t</div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(\".work-mid\").find(\"li\").click(function () {\r\n");
      out.write("        $(\".work-mid\").find(\"li\").css({\r\n");
      out.write("            \"background-color\": \"white\",\r\n");
      out.write("            \"color\": \"black\"\r\n");
      out.write("        });\r\n");
      out.write("        $(this).css({\r\n");
      out.write("            \"background-color\": \"#4286f4\",\r\n");
      out.write("            \"color\": \"white\"\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    $(\".search-btn\").find(\"li\").eq(0).click(function(){\r\n");
      out.write("\t\t$(\".s-tap\").css(\"display\",\"none\");\r\n");
      out.write("\t\t$(\".search-wrap\").css(\"display\",\"block\");\r\n");
      out.write("\t\t$(\".search-btn\").find(\"li\").css(\"background-color\",\"#83b2ff\");\r\n");
      out.write("\t\t$(this).css(\"background-color\",\"#4286f4\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".search-btn\").find(\"li\").eq(1).click(function(){\r\n");
      out.write("\t\t$(\".s-tap\").css(\"display\",\"none\");\r\n");
      out.write("\t\t$(\".work-top\").css(\"display\",\"block\");\r\n");
      out.write("\t\t$(\".work-bot\").css(\"display\",\"block\");\r\n");
      out.write("\t\t$(\".search-btn\").find(\"li\").css(\"background-color\",\"#83b2ff\");\r\n");
      out.write("\t\t$(this).css(\"background-color\",\"#4286f4\");\r\n");
      out.write("\t\t$(\".work-bot\").html(\"\");\r\n");
      out.write("\t\t$(\".paging\").html(\"\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".search-btn\").find(\"li\").eq(2).click(function(){\r\n");
      out.write("\t\t$(\".s-tap\").css(\"display\",\"none\");\r\n");
      out.write("\t\t$(\".work-mid\").css(\"display\",\"block\");\r\n");
      out.write("\t\t$(\".work-bot\").css(\"display\",\"block\");\r\n");
      out.write("\t\t$(\".search-btn\").find(\"li\").css(\"background-color\",\"#83b2ff\");\r\n");
      out.write("\t\t$(this).css(\"background-color\",\"#4286f4\");\r\n");
      out.write("\t\t$(\".work-bot\").html(\"\");\r\n");
      out.write("\t\t$(\".paging\").html(\"\");\r\n");
      out.write("\t});\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/main_tap.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/workPaging.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/mainSearchPaging.js\"></script>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/policy\">이용약관</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/privacy\">개인정보처리방침</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/biz\">사업자정보확인</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/bbc/cs\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>\r\n");
      out.write("            상호 : (주)씨닥 | 대표 : 씨닥 | 개인정보관리책임자 : KH | 전화 : 2588-2588 | 이메일 : khm0627@naver.com\r\n");
      out.write("            <Br />주소 : 서울특별시 강남구 역삼동 | 사업자등록번호 : 110-426-375674 | 통신판매 : 제 2020-서울강남-0922호 | 호스팅제공자 : (주)씨닥\r\n");
      out.write("            <br><br>\r\n");
      out.write("            Copyrighter ⓒ 2020 SeeDoc KH-m\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
