/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-13 00:22:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.docs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class policy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1594081654904L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1594080907083L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/footer.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top-bar\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("                        <li style=\"color:white\">홈</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/login\">\r\n");
      out.write("                        <li>로그인</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/register\">\r\n");
      out.write("                        <li>회원가입</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit-info\">\r\n");
      out.write("                        <li>회원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/mypage\">\r\n");
      out.write("                        <li>예약내역</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sub-bar\"></div>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("section {\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\tpadding-top: 100px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<section>\r\n");
      out.write("\t<div id=\"displayCanvas\">\r\n");
      out.write("\t\t<div id=\"policyPage\"\r\n");
      out.write("\t\t\tclass=\"designSettingElement text-bodyWithLineHeight\">\r\n");
      out.write("\t\t\t<p style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 20px\"><strong>이용약관</strong></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">&nbsp;</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\"><strong>제1조(목적)</strong></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">이 약관은 <strong><span\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: #b12424\">OO 회사</span></strong>(전자상거래 사업자)가 운영하는 <strong><span\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: #b12424\">OO 사이버 SeeDoc</span></strong>(이하 “SeeDoc”이라 한다)에서\r\n");
      out.write("\t\t\t\t\t제공하는 인터넷 관련 서비스(이하 “서비스”라 한다)를 이용함에 있어 사이버 SeeDoc과 이용자의 권리․의무 및\r\n");
      out.write("\t\t\t\t\t책임사항을 규정함을 목적으로 합니다.\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">※「PC통신, 무선 등을 이용하는 전자상거래에 대해서도\r\n");
      out.write("\t\t\t\t\t그 성질에 반하지 않는 한 이 약관을 준용합니다.」</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\"><strong>제2조(정의)</strong></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">① “SeeDoc”이란 <strong><span\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: #b12424\">OO 회사</span></strong>가 재화 또는 용역(이하 “재화 등”이라 함)을\r\n");
      out.write("\t\t\t\t\t이용자에게 제공하기 위하여 컴퓨터 등 정보통신설비를 이용하여 재화 등을 거래할 수 있도록 설정한 가상의 영업장을 말하며,\r\n");
      out.write("\t\t\t\t\t아울러 사이버SeeDoc을 운영하는 사업자의 의미로도 사용합니다.\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">② “이용자”란 “SeeDoc”에 접속하여 이 약관에\r\n");
      out.write("\t\t\t\t\t따라 “SeeDoc”이 제공하는 서비스를 받는 회원 및 비회원을 말합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">③ ‘회원’이라 함은 “SeeDoc”에 회원등록을 한\r\n");
      out.write("\t\t\t\t\t자로서, 계속적으로 “SeeDoc”이 제공하는 서비스를 이용할 수 있는 자를 말합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">④ ‘비회원’이라 함은 회원에 가입하지 않고\r\n");
      out.write("\t\t\t\t\t“SeeDoc”이 제공하는 서비스를 이용하는 자를 말합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\"><strong>제3조 (약관 등의 명시와\r\n");
      out.write("\t\t\t\t\t\t설명 및 개정)&nbsp;</strong></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">① “SeeDoc”은 이 약관의 내용과 상호 및 대표자\r\n");
      out.write("\t\t\t\t\t성명, 영업소 소재지 주소(소비자의 불만을 처리할 수 있는 곳의 주소를 포함), 전화번호․모사전송번호․전자우편주소,\r\n");
      out.write("\t\t\t\t\t사업자등록번호, 통신판매업 신고번호, 개인정보관리책임자등을 이용자가 쉽게 알 수 있도록 <strong><span\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: #b12424\">OO 사이버 SeeDoc</span></strong>의 초기 서비스화면(전면)에 게시합니다.\r\n");
      out.write("\t\t\t\t\t다만, 약관의 내용은 이용자가 연결화면을 통하여 볼 수 있도록 할 수 있습니다.\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">② “SeeDoc은 이용자가 약관에 동의하기에 앞서\r\n");
      out.write("\t\t\t\t\t약관에 정하여져 있는 내용 중 청약철회․배송책임․환불조건 등과 같은 중요한 내용을 이용자가 이해할 수 있도록 별도의\r\n");
      out.write("\t\t\t\t\t연결화면 또는 팝업화면 등을 제공하여 이용자의 확인을 구하여야 합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">③ “SeeDoc”은 「전자상거래 등에서의 소비자보호에\r\n");
      out.write("\t\t\t\t\t관한 법률」, 「약관의 규제에 관한 법률」, 「전자문서 및 전자거래기본법」, 「전자금융거래법」, 「전자서명법」,\r\n");
      out.write("\t\t\t\t\t「정보통신망 이용촉진 및 정보보호 등에 관한 법률」, 「방문판매 등에 관한 법률」, 「소비자기본법」 등 관련 법을\r\n");
      out.write("\t\t\t\t\t위배하지 않는 범위에서 이 약관을 개정할 수 있습니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">④ “SeeDoc”이 약관을 개정할 경우에는 적용일자 및\r\n");
      out.write("\t\t\t\t\t개정사유를 명시하여 현행약관과 함께 SeeDoc의 초기화면에 그 적용일자 7일 이전부터 적용일자 전일까지 공지합니다.\r\n");
      out.write("\t\t\t\t\t다만, 이용자에게 불리하게 약관내용을 변경하는 경우에는 최소한 30일 이상의 사전 유예기간을 두고 공지합니다.이 경우\r\n");
      out.write("\t\t\t\t\t\"SeeDoc“은 개정 전 내용과 개정 후 내용을 명확하게 비교하여 이용자가 알기 쉽도록 표시합니다.&nbsp;</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">⑤ “SeeDoc”이 약관을 개정할 경우에는 그\r\n");
      out.write("\t\t\t\t\t개정약관은 그 적용일자 이후에 체결되는 계약에만 적용되고 그 이전에 이미 체결된 계약에 대해서는 개정 전의 약관조항이\r\n");
      out.write("\t\t\t\t\t그대로 적용됩니다. 다만 이미 계약을 체결한 이용자가 개정약관 조항의 적용을 받기를 원하는 뜻을 제3항에 의한 개정약관의\r\n");
      out.write("\t\t\t\t\t공지기간 내에 “SeeDoc”에 송신하여 “SeeDoc”의 동의를 받은 경우에는 개정약관 조항이 적용됩니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">⑥ 이 약관에서 정하지 아니한 사항과 이 약관의 해석에\r\n");
      out.write("\t\t\t\t\t관하여는 전자상거래 등에서의 소비자보호에 관한 법률, 약관의 규제 등에 관한 법률, 공정거래위원회가 정하는 전자상거래\r\n");
      out.write("\t\t\t\t\t등에서의 소비자 보호지침 및 관계법령 또는 상관례에 따릅니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<strong><span style=\"font-size: 14px\">제4조(서비스의 제공 및\r\n");
      out.write("\t\t\t\t\t\t변경)&nbsp;</span></strong>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">① “SeeDoc”은 다음과 같은 업무를 수행합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">1. 재화 또는 용역에 대한 정보 제공 및 구매계약의\r\n");
      out.write("\t\t\t\t\t체결<br> 2. 구매계약이 체결된 재화 또는 용역의 배송<br> 3. 기타 “SeeDoc”이 정하는\r\n");
      out.write("\t\t\t\t\t업무\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">② “SeeDoc”은 재화 또는 용역의 품절 또는 기술적\r\n");
      out.write("\t\t\t\t\t사양의 변경 등의 경우에는 장차 체결되는 계약에 의해 제공할 재화 또는 용역의 내용을 변경할 수 있습니다. 이 경우에는\r\n");
      out.write("\t\t\t\t\t변경된 재화 또는 용역의 내용 및 제공일자를 명시하여 현재의 재화 또는 용역의 내용을 게시한 곳에 즉시 공지합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">③ “SeeDoc”이 제공하기로 이용자와 계약을 체결한\r\n");
      out.write("\t\t\t\t\t서비스의 내용을 재화등의 품절 또는 기술적 사양의 변경 등의 사유로 변경할 경우에는 그 사유를 이용자에게 통지 가능한\r\n");
      out.write("\t\t\t\t\t주소로 즉시 통지합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">④ 전항의 경우 “SeeDoc”은 이로 인하여 이용자가\r\n");
      out.write("\t\t\t\t\t입은 손해를 배상합니다. 다만, “SeeDoc”이 고의 또는 과실이 없음을 입증하는 경우에는 그러하지 아니합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<strong><span style=\"font-size: 14px\">제5조(서비스의\r\n");
      out.write("\t\t\t\t\t\t중단)&nbsp;</span></strong>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">① “SeeDoc”은 컴퓨터 등 정보통신설비의\r\n");
      out.write("\t\t\t\t\t보수점검․교체 및 고장, 통신의 두절 등의 사유가 발생한 경우에는 서비스의 제공을 일시적으로 중단할 수 있습니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">② “SeeDoc”은 제1항의 사유로 서비스의 제공이\r\n");
      out.write("\t\t\t\t\t일시적으로 중단됨으로 인하여 이용자 또는 제3자가 입은 손해에 대하여 배상합니다. 단, “SeeDoc”이 고의 또는\r\n");
      out.write("\t\t\t\t\t과실이 없음을 입증하는 경우에는 그러하지 아니합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">③ 사업종목의 전환, 사업의 포기, 업체 간의 통합 등의\r\n");
      out.write("\t\t\t\t\t이유로 서비스를 제공할 수 없게 되는 경우에는 “SeeDoc”은 제8조에 정한 방법으로 이용자에게 통지하고 당초\r\n");
      out.write("\t\t\t\t\t“SeeDoc”에서 제시한 조건에 따라 소비자에게 보상합니다. 다만, “SeeDoc”이 보상기준 등을 고지하지 아니한\r\n");
      out.write("\t\t\t\t\t경우에는 이용자들의 마일리지 또는 적립금 등을 “SeeDoc”에서 통용되는 통화가치에 상응하는 현물 또는 현금으로\r\n");
      out.write("\t\t\t\t\t이용자에게 지급합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<strong><span style=\"font-size: 14px\">제6조(회원가입)&nbsp;</span></strong>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">① 이용자는 “SeeDoc”이 정한 가입 양식에 따라\r\n");
      out.write("\t\t\t\t\t회원정보를 기입한 후 이 약관에 동의한다는 의사표시를 함으로서 회원가입을 신청합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">② “SeeDoc”은 제1항과 같이 회원으로 가입할 것을\r\n");
      out.write("\t\t\t\t\t신청한 이용자 중 다음 각 호에 해당하지 않는 한 회원으로 등록합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">1. 가입신청자가 이 약관 제7조제3항에 의하여 이전에\r\n");
      out.write("\t\t\t\t\t회원자격을 상실한 적이 있는 경우, 다만 제7조제3항에 의한 회원자격 상실 후 3년이 경과한 자로서 “SeeDoc”의\r\n");
      out.write("\t\t\t\t\t회원재가입 승낙을 얻은 경우에는 예외로 한다.<br> 2. 등록 내용에 허위, 기재누락, 오기가 있는 경우<br>\r\n");
      out.write("\t\t\t\t\t3. 기타 회원으로 등록하는 것이 “SeeDoc”의 기술상 현저히 지장이 있다고 판단되는 경우\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">③ 회원가입계약의 성립 시기는 “SeeDoc”의 승낙이\r\n");
      out.write("\t\t\t\t\t회원에게 도달한 시점으로 합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">④ 회원은 회원가입 시 등록한 사항에 변경이 있는 경우,\r\n");
      out.write("\t\t\t\t\t상당한 기간 이내에 “SeeDoc”에 대하여 회원정보 수정 등의 방법으로 그 변경사항을 알려야 합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<strong><span style=\"font-size: 14px\">제7조(회원 탈퇴 및 자격\r\n");
      out.write("\t\t\t\t\t\t상실 등)&nbsp;</span></strong>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">① 회원은 “SeeDoc”에 언제든지 탈퇴를 요청할 수\r\n");
      out.write("\t\t\t\t\t있으며 “SeeDoc”은 즉시 회원탈퇴를 처리합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">② 회원이 다음 각 호의 사유에 해당하는 경우,\r\n");
      out.write("\t\t\t\t\t“SeeDoc”은 회원자격을 제한 및 정지시킬 수 있습니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">1. 가입 신청 시에 허위 내용을 등록한 경우<br>\r\n");
      out.write("\t\t\t\t\t2. “SeeDoc”을 이용하여 구입한 재화 등의 대금, 기타 “SeeDoc”이용에 관련하여 회원이 부담하는 채무를\r\n");
      out.write("\t\t\t\t\t기일에 지급하지 않는 경우<br> 3. 다른 사람의 “SeeDoc” 이용을 방해하거나 그 정보를 도용하는 등\r\n");
      out.write("\t\t\t\t\t전자상거래 질서를 위협하는 경우<br> 4. “SeeDoc”을 이용하여 법령 또는 이 약관이 금지하거나\r\n");
      out.write("\t\t\t\t\t공서양속에 반하는 행위를 하는 경우\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">③ “SeeDoc”이 회원 자격을 제한․정지 시킨 후,\r\n");
      out.write("\t\t\t\t\t동일한 행위가 2회 이상 반복되거나 30일 이내에 그 사유가 시정되지 아니하는 경우 “SeeDoc”은 회원자격을 상실시킬\r\n");
      out.write("\t\t\t\t\t수 있습니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">④ “SeeDoc”이 회원자격을 상실시키는 경우에는\r\n");
      out.write("\t\t\t\t\t회원등록을 말소합니다. 이 경우 회원에게 이를 통지하고, 회원등록 말소 전에 최소한 30일 이상의 기간을 정하여 소명할\r\n");
      out.write("\t\t\t\t\t기회를 부여합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<strong><span style=\"font-size: 14px\">제8조(회원에 대한 통지)</span></strong>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">① “SeeDoc”이 회원에 대한 통지를 하는 경우,\r\n");
      out.write("\t\t\t\t\t회원이 “SeeDoc”과 미리 약정하여 지정한 전자우편 주소로 할 수 있습니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">② “SeeDoc”은 불특정다수 회원에 대한 통지의 경우\r\n");
      out.write("\t\t\t\t\t1주일이상 “SeeDoc” 게시판에 게시함으로서 개별 통지에 갈음할 수 있습니다. 다만, 회원 본인의 거래와 관련하여\r\n");
      out.write("\t\t\t\t\t중대한 영향을 미치는 사항에 대하여는 개별통지를 합니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<strong><span style=\"font-size: 14px\">제9조(구매신청 및\r\n");
      out.write("\t\t\t\t\t\t개인정보 제공 동의 등)&nbsp;</span></strong>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">① “SeeDoc”이용자는 “SeeDoc”상에서 다음\r\n");
      out.write("\t\t\t\t\t또는 이와 유사한 방법에 의하여 구매를 신청하며, “SeeDoc”은 이용자가 구매신청을 함에 있어서 다음의 각 내용을\r\n");
      out.write("\t\t\t\t\t알기 쉽게 제공하여야 합니다.&nbsp;</span><br> &nbsp;\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">1. 재화 등의 검색 및 선택<br> 2. 받는\r\n");
      out.write("\t\t\t\t\t사람의 성명, 주소, 전화번호, 전자우편주소(또는 이동전화번호) 등의 입력<br> 3. 약관내용, 청약철회권이\r\n");
      out.write("\t\t\t\t\t제한되는 서비스, 배송료․설치비 등의 비용부담과 관련한 내용에 대한 확인<br> 4. 이 약관에 동의하고 위\r\n");
      out.write("\t\t\t\t\t3.호의 사항을 확인하거나 거부하는 표시(예, 마우스 클릭)<br> 5. 재화등의 구매신청 및 이에 관한 확인\r\n");
      out.write("\t\t\t\t\t또는 “SeeDoc”의 확인에 대한 동의<br> 6. 결제방법의 선택\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">② “SeeDoc”이 제3자에게 구매자 개인정보를 제공할\r\n");
      out.write("\t\t\t\t\t필요가 있는 경우 1) 개인정보를 제공받는 자, 2)개인정보를 제공받는 자의 개인정보 이용목적, 3) 제공하는 개인정보의\r\n");
      out.write("\t\t\t\t\t항목, 4) 개인정보를 제공받는 자의 개인정보 보유 및 이용기간을 구매자에게 알리고 동의를 받아야 합니다. (동의를 받은\r\n");
      out.write("\t\t\t\t\t사항이 변경되는 경우에도 같습니다.)</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">③ “SeeDoc”이 제3자에게 구매자의 개인정보를\r\n");
      out.write("\t\t\t\t\t취급할 수 있도록 업무를 위탁하는 경우에는 1) 개인정보 취급위탁을 받는 자, 2) 개인정보 취급위탁을 하는 업무의\r\n");
      out.write("\t\t\t\t\t내용을 구매자에게 알리고 동의를 받아야 합니다. (동의를 받은 사항이 변경되는 경우에도 같습니다.) 다만, 서비스제공에\r\n");
      out.write("\t\t\t\t\t관한 계약이행을 위해 필요하고 구매자의 편의증진과 관련된 경우에는 「정보통신망 이용촉진 및 정보보호 등에 관한 법률」에서\r\n");
      out.write("\t\t\t\t\t정하고 있는 방법으로 개인정보 취급방침을 통해 알림으로써 고지절차와 동의절차를 거치지 않아도 됩니다.</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">&nbsp;</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">부 칙(시행일) 이 약관은&nbsp;<strong><span\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: #b12424\">2020년 7월 1일</span></strong>부터 시행합니다.\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">&nbsp;</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">&nbsp;</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">&nbsp;</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">&nbsp;</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 14px\">&nbsp;</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/policy\">이용약관</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/privacy\">개인정보처리방침</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/biz\">사업자정보확인</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/bbc/cs\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>\r\n");
      out.write("            상호 : (주)씨닥 | 대표 : 씨닥 | 개인정보관리책임자 : KH | 전화 : 2588-2588 | 이메일 : khm0627@naver.com\r\n");
      out.write("            <Br />주소 : 서울특별시 강남구 역삼동 | 사업자등록번호 : 110-426-375674 | 통신판매 : 제 2020-서울강남-0922호 | 호스팅제공자 : (주)씨닥\r\n");
      out.write("            <br><br>\r\n");
      out.write("            Copyrighter ⓒ 2020 SeeDoc KH-m\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
