/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-20 07:08:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hospital;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import hospital.model.vo.HospFile;
import hospital.model.vo.HospDoctor;
import java.util.List;
import member.model.service.MemberService;
import member.model.vo.User;
import hospital.model.vo.Hospital;

public final class docList_002dView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1595158624000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1595220082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("hospital.model.vo.HospFile");
    _jspx_imports_classes.add("member.model.vo.User");
    _jspx_imports_classes.add("hospital.model.vo.Hospital");
    _jspx_imports_classes.add("hospital.model.vo.HospDoctor");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	Cookie[] cookies2 = request.getCookies();
	boolean saveUserIdChecked = false;
	String saveUserIdValue = "";
	if(cookies2 != null) {
		for(Cookie c : cookies2) {
			String k = c.getName();
			String v = c.getValue();

			if("saveUserId".equals(k)) {
				saveUserIdChecked = true;
				saveUserIdValue = v;
			}
		}
	}
	
	
	
	Hospital hospLoggedIn = (Hospital)session.getAttribute("hospLoggedIn");
	//쿠키관련
	Cookie[] cookies = request.getCookies();
	boolean saveHospIdChecked = false;
	String saveHospIdValue = "";
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();

			if("saveHospId".equals(k)) {
				saveHospIdChecked = true;
				saveHospIdValue = v;
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>See Doctor</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/footer.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top-bar\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <ul>\r\n");
      out.write("                ");
if(hospLoggedIn == null && userLoggedIn == null) { 
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("                        <li style=\"color:white\">홈</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/login\">\r\n");
      out.write("                        <li>로그인</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/register\">\r\n");
      out.write("                        <li>회원가입</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else if(hospLoggedIn != null) { 
      out.write("\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"><span class=\"login1\"><strong>");
      out.print( hospLoggedIn.getHospName() );
      out.write("</strong></span></a>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/edit-info?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>병원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/doctorList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>의사보기</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingHopitalList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역(병원)</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                 ");
}else if(userLoggedIn!=null&&userLoggedIn.getUserRole().equals(MemberService.MEMBER_ROLE_ADMIN)){ 
      out.write("   \r\n");
      out.write("                    <span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">\r\n");
      out.write("                        <li>회원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/hospList\">\r\n");
      out.write("                        <li>병원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                \t<span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit-info?userId=");
      out.print( userLoggedIn.getUserId());
      out.write("\">\r\n");
      out.write("                        <li>회원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookinglist?userId=");
      out.print( userLoggedIn.getUserId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sub-bar\"></div>\r\n");
      out.write('\r');
      out.write('\n');

	Hospital h = (Hospital)request.getAttribute("h");
	List<HospFile> fileList = (List<HospFile>)request.getAttribute("hospFileList");
	List<HospDoctor> list = (List<HospDoctor>)request.getAttribute("list");
	String pageBar = (String)request.getAttribute("pageBar");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function fileDownload(oname, rname) {\r\n");
      out.write("\tlet url = \"");
      out.print(request.getContextPath());
      out.write("/board/fileDownload\";\r\n");
      out.write("\t//한글을 %문자(유니코드)로 변경\r\n");
      out.write("\toname = encodeURIComponent(oname); //한글이 주소에 들어가면 IE에서 오류남 --> 인코딩처리\r\n");
      out.write("\tconsole.log(oname);\r\n");
      out.write("\tlocation.href = url+\"?oname=\"+oname+\"&rname=\"+rname;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/docList-view.css\">\r\n");
      out.write("<section>\r\n");
      out.write("        <div class=\"bk-logo-wrap\">\r\n");
      out.write("        \t<div class=\"hos-logo\">\r\n");
      out.write("            ");
 for(HospFile hf: fileList) { 
      out.write("\r\n");
      out.write("        \t\t");
 if("logo".equals(hf.getUse()) && hf.getBoardOriginalFileName()!=null){ 
      out.write("\r\n");
      out.write("        \t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/hospital/");
      out.print(hf.getBoardRenamedFileName() );
      out.write("\" alt=\"\">\r\n");
      out.write("\t        \t");
 } else if("logo".equals(hf.getUse()) && hf.getBoardOriginalFileName()==null){ 
      out.write("\r\n");
      out.write("\t        \t\t<p style=\"font-size: 39px; margin-top: 100px; font-weight: 800; color: white;position: relative; z-index: 1;\">");
      out.print(h.getHospName() );
      out.write("</p>\r\n");
      out.write("        \t\t");
 } 
      out.write("\r\n");
      out.write("        \t\t");
 if("thumbnail".equals(hf.getUse()) && hf.getBoardOriginalFileName()!=null){ 
      out.write("\r\n");
      out.write("        \t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/hospital/");
      out.print(hf.getBoardRenamedFileName() );
      out.write("\" alt=\"\">\r\n");
      out.write("\t        \t");
 } else if("thumbnail".equals(hf.getUse()) && hf.getBoardOriginalFileName()==null){ 
      out.write("\r\n");
      out.write("\t        \t\t<p style=\"font-size: 26px; margin-top: 100px; font-weight: 800; color: white;position: relative; z-index: 1;\">메인 이미지를 등록해주세요.</p>\r\n");
      out.write("        \t\t");
 } 
      out.write("\r\n");
      out.write("        \t");
 } 
      out.write("\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("            <div class=\"opa-back\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h1 class=\"title\"><span>●</span>");
      out.print( h.getHospName() );
      out.write(" 의사리스트보기</h1>\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/doctorRegister?hospId=");
      out.print( h.getHospId() );
      out.write("\" class=\"add-doc\">\r\n");
      out.write("        \t의사추가\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("\t    ");
if(list == null || list.isEmpty()) {
      out.write("\r\n");
      out.write("\t    \t<h1>조회된 의사가 없습니다.</h1>   \r\n");
      out.write("        ");
 }else { 
        		for(HospDoctor hd : list) {
        
      out.write("\r\n");
      out.write("        <div class=\"bk-main-wrap\">\r\n");
      out.write("            <div class=\"doc-wrap\">\r\n");
      out.write("                ");
 if(!fileList.isEmpty()) { 
                		for(HospFile fl : fileList) {
 		            		if(fl.getDoctorNo() != null) {
                				if((fl.getDoctorNo()).equals(hd.getDoctorNo())) { 
                					if(fl.getBoardOriginalFileName() != null) { 
                				
      out.write("\r\n");
      out.write("\t\t\t\t\t                <div class=\"doc-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img alt=\"의사이미지\" src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/hospital/");
      out.print(fl.getBoardRenamedFileName() );
      out.write("\">\r\n");
      out.write("                \t\t\t\t\t</div>\r\n");
      out.write("                \t\t\t\t\t");
}else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t                <div class=\"doc-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img alt=\"의사이미지\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/doctor.png\">\r\n");
      out.write("                \t\t\t\t\t</div>\r\n");
      out.write("                \t");
				}
				 				}	
							} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t                ");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 		}
 		            	}
                	} else {
      out.write("\r\n");
      out.write("                \t<div class=\"doc-img\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"의사이미지\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/doctor.png\">\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("                \t");
 } 
      out.write("\r\n");
      out.write("                <div class=\"doc-info\">\r\n");
      out.write("                    <h1>");
      out.print(hd.getDoctorName() );
      out.write("님</h1>\r\n");
      out.write("                    <p> - 의사번호 : ");
      out.print( hd.getDoctorNo() );
      out.write("</p>\r\n");
      out.write("                    <p> - 진료과 : ");
      out.print( hd.getHospDept() );
      out.write("</p>\r\n");
      out.write("                    <p> - 진료내용 : ");
      out.print( hd.getDoctorTreat()==null ? "":hd.getDoctorTreat());
      out.write("</p>\r\n");
      out.write("                    <p> - 학력/전공 : ");
      out.print( hd.getDoctorSpec()==null ? "":hd.getDoctorSpec());
      out.write("</p>\r\n");
      out.write("                    <button onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/hospital/doctorEdit?hospId=");
      out.print(hd.getHospId() );
      out.write("&doctorNo=");
      out.print( hd.getDoctorNo() );
      out.write("'\">수정하기</button>\r\n");
      out.write("                    <button onclick=\"deleteDoc();\">삭제하기</button>\r\n");
      out.write("                  \t");
      out.write("\r\n");
      out.write("                  \t<script>\r\n");
      out.write("                  \tfunction deleteDoc() {\r\n");
      out.write("                  \t\tif(!confirm('이 의사정보를 삭제하시겠습니까?')) return;\r\n");
      out.write("                  \t\tlocation.href='");
      out.print(request.getContextPath());
      out.write("/hospital/doctorDelete?hospId=");
      out.print(hd.getHospId() );
      out.write("&doctorNo=");
      out.print( hd.getDoctorNo() );
      out.write("';\r\n");
      out.write("                  \t}\r\n");
      out.write("                  \t</script>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       ");
 		}
        	}
      out.write("\r\n");
      out.write("<div id='pageBar' style=\"color:black;\">\r\n");
      out.write("\t\t");
      out.print( pageBar );
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/policy\">이용약관</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/privacy\">개인정보처리방침</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/biz\">사업자정보확인</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/bbc/cs\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>\r\n");
      out.write("            상호 : (주)씨닥 | 대표 : 씨닥 | 개인정보관리책임자 : KH | 전화 : 2588-2588 | 이메일 : khm0627@naver.com\r\n");
      out.write("            <Br />주소 : 서울특별시 강남구 역삼동 | 사업자등록번호 : 110-426-375674 | 통신판매 : 제 2020-서울강남-0922호 | 호스팅제공자 : (주)씨닥\r\n");
      out.write("            <br><br>\r\n");
      out.write("            Copyrighter ⓒ 2020 SeeDoc KH-m\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
