/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-20 06:10:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hospital;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import hospital.model.vo.HospFile;
import hospital.model.vo.HospTime;
import java.util.Arrays;
import java.util.List;
import member.model.service.MemberService;
import member.model.vo.User;
import hospital.model.vo.Hospital;

public final class edit_002dinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1595158624000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1595220082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("hospital.model.vo.HospFile");
    _jspx_imports_classes.add("hospital.model.vo.HospTime");
    _jspx_imports_classes.add("member.model.vo.User");
    _jspx_imports_classes.add("hospital.model.vo.Hospital");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	Cookie[] cookies2 = request.getCookies();
	boolean saveUserIdChecked = false;
	String saveUserIdValue = "";
	if(cookies2 != null) {
		for(Cookie c : cookies2) {
			String k = c.getName();
			String v = c.getValue();

			if("saveUserId".equals(k)) {
				saveUserIdChecked = true;
				saveUserIdValue = v;
			}
		}
	}
	
	
	
	Hospital hospLoggedIn = (Hospital)session.getAttribute("hospLoggedIn");
	//쿠키관련
	Cookie[] cookies = request.getCookies();
	boolean saveHospIdChecked = false;
	String saveHospIdValue = "";
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();

			if("saveHospId".equals(k)) {
				saveHospIdChecked = true;
				saveHospIdValue = v;
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>See Doctor</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/footer.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top-bar\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <ul>\r\n");
      out.write("                ");
if(hospLoggedIn == null && userLoggedIn == null) { 
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("                        <li style=\"color:white\">홈</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/login\">\r\n");
      out.write("                        <li>로그인</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/register\">\r\n");
      out.write("                        <li>회원가입</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else if(hospLoggedIn != null) { 
      out.write("\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"><span class=\"login1\"><strong>");
      out.print( hospLoggedIn.getHospName() );
      out.write("</strong></span></a>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/edit-info?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>병원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/doctorList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>의사보기</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingHopitalList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역(병원)</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                 ");
}else if(userLoggedIn!=null&&userLoggedIn.getUserRole().equals(MemberService.MEMBER_ROLE_ADMIN)){ 
      out.write("   \r\n");
      out.write("                    <span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">\r\n");
      out.write("                        <li>회원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/hospList\">\r\n");
      out.write("                        <li>병원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                \t<span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit-info?userId=");
      out.print( userLoggedIn.getUserId());
      out.write("\">\r\n");
      out.write("                        <li>회원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookinglist?userId=");
      out.print( userLoggedIn.getUserId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sub-bar\"></div>\r\n");
      out.write('\n');

	Hospital h = (Hospital)request.getAttribute("h");
	HospTime ht = (HospTime)request.getAttribute("ht");
	List<HospFile> hospFileList = (List<HospFile>)request.getAttribute("hospFileList");
	String hospInfo = h.getHospInfo() != null ? h.getHospInfo() : "";
	//System.out.println(hospFileList.isEmpty());
	//String hospConv = hospLoggedIn.getHospConv();
	//List<String> convList = null;
	//if(hospConv != null) {
	//	String[] convArr = hospConv.split(",");
	//	convList = Arrays.asList(convArr);
	//}
//	System.out.println("convList = "+convList);

      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/edit-info.css\">\n");
      out.write("<script>\n");
      out.write("$(function() {\n");
      out.write("\t$(\"#hospPwdCheck\").keyup(function () {\n");
      out.write("\t\t//console.log(\"실행\");\n");
      out.write("\t\tlet $pwd1 = $(\"#hospPwd\");\n");
      out.write("\t\tlet $pwd2 = $(\"#hospPwdCheck\");\n");
      out.write("\t    \n");
      out.write("\t    if($pwd1.val() == $pwd2.val()){\n");
      out.write("\t        $('#p-pwdCheck').css('opacity', '0');\n");
      out.write("\t        return true;\n");
      out.write("\t    }\n");
      out.write("\t    else{\n");
      out.write("\t        $('#p-pwdCheck').css('opacity', '1');\n");
      out.write("\t        return false;\n");
      out.write("\t    }\n");
      out.write("\t});\n");
      out.write("\t$(\"[name=hospitalUpdateFrm]\").submit(function() {\n");
      out.write("\t\t//비밀번호검사\n");
      out.write("\t\tlet $pwd1 = $(\"#hospPwd\");\n");
      out.write("\t\tlet $pwd2 = $(\"#hospPwdCheck\");\n");
      out.write("\t\tif($pwd1.val() !== $pwd2.val()) {\n");
      out.write("\t\t\t$('#p-pwdCheck').css('opacity', '1');\n");
      out.write("\t\t\t$pwd1.focus();\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\treturn true;\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("function deleteHospital() {\n");
      out.write("\tif(!confirm(\"정말 탈퇴하시겠습니까?\")) return;\n");
      out.write("\t\n");
      out.write("\t$(\"[name=deleteHospitalFrm]\").submit();\n");
      out.write("}\n");
      out.write("function openPopup() {\n");
      out.write("\t//팝업생성\n");
      out.write("\tlet url = \"");
      out.print( request.getContextPath() );
      out.write("/jusoPopup\";\n");
      out.write("\tlet title = \"jusoPopup\";\n");
      out.write("\tlet spec = \"left=300px, top=300px, width=600px, height=500px\";\n");
      out.write("\topen(url, title, spec);\n");
      out.write("\n");
      out.write("}\n");
      out.write("function jusoCallBack(roadFullAddr,roadAddrPart1,addrDetail,roadAddrPart2,engAddr, jibunAddr, zipNo, admCd, rnMgtSn, bdMgtSn,detBdNmList,bdNm,bdKdcd,siNm,sggNm,emdNm,liNm,rn,udrtYn,buldMnnm,buldSlno,mtYn,lnbrMnnm,lnbrSlno,emdNo){\n");
      out.write("\n");
      out.write("    // 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\n");
      out.write("\t//console.log(roadFullAddr);\n");
      out.write("\t$(\"#hospAddr\").val(roadFullAddr); // 도로명주소\n");
      out.write("\n");
      out.write("\t//document.form.addrDetail.value = addrDetail; // 상세주소\n");
      out.write("\n");
      out.write("\t//document.form.zipNo.value = zipNo; // 우편번호\n");
      out.write("\n");
      out.write("\tself.close();\n");
      out.write("\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<section>\n");
      out.write("        <article>\n");
      out.write("            <div class=\"register\">\n");
      out.write("                <h1 id=\"title\">병원정보수정</h1>\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath() );
      out.write("/hospital/deleteHospital\" name=\"deleteHospitalFrm\" method=\"POST\">\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print(h.getHospId() );
      out.write("\" />\n");
      out.write("\t\t\t\t</form>\n");
      out.write("                \t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/hospital/edit-info\" name=\"hospitalUpdateFrm\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                \t\t\t<p style=\"color: red; font-size: 12px;\">*표시 항목은 필수 항목입니다.</p>\n");
      out.write("\t\t                    <input type=\"hidden\" class=\"user-input check-input\" name=\"hospId\" id=\"hospId\" value=\"");
      out.print( h.getHospId());
      out.write("\" readonly>\n");
      out.write("\t\t                    <label class=\"text-label\">비밀번호<span>*</span></label>\n");
      out.write("\t\t                    <input type=\"password\" class=\"user-input\" name=\"hospPwd\" id=\"hospPwd\" required>\n");
      out.write("\t\t                    <input type=\"password\" placeholder=\"비밀번호 확인\" class=\"user-input\" name=\"hospPwdCheck\" id=\"hospPwdCheck\" required>\n");
      out.write("\t\t                    <p id=\"p-pwdCheck\" style=\"color:red; font-size:12px; opacity:0;\">비밀번호가 일치하지 않습니다.</p>\n");
      out.write("\t\t\n");
      out.write("\t\t                    <label class=\"text-label\">병원이름<span>*</span></label>\n");
      out.write("\t\t                    <input type=\"text\" class=\"user-input\" name=\"hospName\" id=\"hospName\" value=\"");
      out.print( h.getHospName() );
      out.write("\" required>\n");
      out.write("\t\t\n");
      out.write("\t\t                    <label class=\"text-label\">병원전화번호 ('-'포함)<span>*</span></label>\n");
      out.write("\t\t                    <input type=\"text\" class=\"user-input\" name=\"hospTel\" id=\"hospTel\" value=\"");
      out.print( h.getHospTel() );
      out.write("\" required>\n");
      out.write("\t\t\n");
      out.write("\t\t                    <label class=\"text-label\">주소<span>*</span></label>\n");
      out.write("\t\t                    <input type=\"text\" class=\"user-input check-input\" name=\"hospAddr\" id=\"hospAddr\" value=\"");
      out.print( h.getHospAddr() );
      out.write("\" required>\n");
      out.write("\t\t                    <div class=\"check-btn\" onclick=\"openPopup();\">우편번호 검색</div>\n");
      out.write("\t\t\t                    <input type=\"text\" class=\"user-input\" placeholder=\"우편번호 주소\">\n");
      out.write("\t\t\t                    <input type=\"text\" class=\"user-input\" placeholder=\"상세주소\">\n");
      out.write("\t\t                    <label class=\"text-label\" >병원소개글</label>\n");
      out.write("\t\t                    <textarea name=\"hospInfo\" id=\"hospInfo\" class=\"user-input\" cols=\"30\" rows=\"30\" style=\"padding:9px 9px; resize: none; height: 100px;\">");
      out.print( hospInfo );
      out.write("</textarea>\n");
      out.write("\t\t                    \n");
      out.write("\t\t                    <fieldset>\n");
      out.write("\t\t                    <legend class=\"text-label\">병원사진</legend>\n");
      out.write("\t\t                    ");
 if(!hospFileList.isEmpty()) {
		                    		int a=1;
		                    		for(HospFile fl : hospFileList) {
		                    			if("logo".equals(fl.getUse())) {
		                    
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"\">로고사진</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(fl.getBoardOriginalFileName()==null ? "":fl.getBoardOriginalFileName() );
      out.write(" <br />\n");
      out.write("\t                    \t\t\t\t<input type=\"file\" name=\"upFile");
      out.print(a++);
      out.write("\" style=\"width:200px;\">\n");
      out.write("\t                    \t\t\t\t<input type=\"checkbox\" name=\"delFile1\" id=\"delFile1\" value=\"사진삭제\"/>\n");
      out.write("\t                    \t\t\t\t<label for=\"delFile1\">사진삭제</label><br />\n");
      out.write("\t                    \t\t\t\t<input type=\"hidden\" name=\"oldOriginalFileName1\" value = \"");
      out.print( fl.getBoardOriginalFileName()==null ? "":fl.getBoardOriginalFileName());
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"oldRenamedFileName1\" value = \"");
      out.print(fl.getBoardRenamedFileName()==null ? "":fl.getBoardRenamedFileName() );
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t");
   		} else if("thumbnail".equals(fl.getUse())) {
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"\">대표이미지</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(fl.getBoardOriginalFileName()==null ? "":fl.getBoardOriginalFileName() );
      out.write("<br />\n");
      out.write("\t                    \t\t\t\t<input type=\"file\" name=\"upFile");
      out.print(a++);
      out.write("\" style=\"width:200px;\">\n");
      out.write("\t                    \t\t\t\t<input type=\"checkbox\" name=\"delFile2\" id=\"delFile2\" value=\"사진삭제\"/>\n");
      out.write("\t                    \t\t\t\t<label for=\"delFile2\">사진삭제</label><br />\n");
      out.write("\t                    \t\t\t\t<input type=\"hidden\" name=\"oldOriginalFileName2\" value = \"");
      out.print(fl.getBoardOriginalFileName()==null ? "":fl.getBoardOriginalFileName());
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"oldRenamedFileName2\" value = \"");
      out.print(fl.getBoardRenamedFileName()==null ? "":fl.getBoardRenamedFileName() );
      out.write("\" />\n");
      out.write("\t\t                    ");
			} else { 
      out.write("\n");
      out.write("\t\t                    \t\t\t<div class=\"filebox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"\">로고사진</label><br />\n");
      out.write("\t\t\t\t\t\t                    <input type=\"file\" name=\"upFile1\" id=\"up_file\" class=\"upload-hidden\" style=\"width:200px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"\">대표이미지</label><br />\n");
      out.write("\t\t\t\t\t                    \t<input type=\"file\" name=\"upFile2\" id=\"up_file2\" class=\"upload-hidden\" style=\"width:200px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t                    \t\t\n");
      out.write("\t\t                    ");
 			}
		                    		}	
		                    	}else if(hospFileList.isEmpty()) {
		                    	//oldOriginalFileName없을때는 insert
		                    	
      out.write("\n");
      out.write("\t                    \t\t\t<div class=\"filebox\">\n");
      out.write("\t                    \t\t\t\t<label for=\"up_file\">로고이미지</label>\n");
      out.write("\t\t\t\t\t                    <input type=\"file\" name=\"upFile1\" id=\"up_file\" class=\"upload-hidden\">\n");
      out.write("\t                    \t\t\t\t<label for=\"up_file2\">대표이미지</label>\n");
      out.write("\t\t\t\t                    \t<input type=\"file\" name=\"upFile2\" id=\"up_file2\" class=\"upload-hidden\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t                    \t");
 } 
      out.write("\n");
      out.write("\t\t                    </fieldset>\n");
      out.write("\t\t                    <fieldset>\n");
      out.write("\t\t                    <legend class=\"text-label\">편의시설</legend>\n");
      out.write("\t\t                    <input type=\"checkbox\" name=\"HospConv\" id=\"wifi\" value=\"무선인터넷\" ");
      out.print( h.getHospConv() != null && h.getHospConv().contains("인터넷")? "checked":"");
      out.write("/>\n");
      out.write("\t\t                    <label for=\"wifi\">무선인터넷</label>\n");
      out.write("\t\t                    <input type=\"checkbox\" name=\"HospConv\" id=\"conv\" value=\"장애인 편의시설\" ");
      out.print( h.getHospConv() != null && h.getHospConv().contains("장애인")? "checked":"");
      out.write("/>\n");
      out.write("\t\t                    <label for=\"conv\">장애인 편의시설</label><br />\n");
      out.write("\t\t                    <input type=\"checkbox\" name=\"HospConv\" id=\"toilet\" value=\"남/녀 화장실 구분\" ");
      out.print( h.getHospConv() != null && h.getHospConv().contains("화장실")? "checked":"");
      out.write("/>\n");
      out.write("\t\t                    <label for=\"toilet\">남/녀 화장실 구분</label>\n");
      out.write("\t\t                    <input type=\"checkbox\" name=\"HospConv\" id=\"parking\" value=\"주차\" ");
      out.print( h.getHospConv() != null && h.getHospConv().contains("주차")? "checked":"");
      out.write("/>\n");
      out.write("\t\t                    <label for=\"parking\">주차</label><br />\n");
      out.write("\t\t                    <input type=\"checkbox\" name=\"HospConv\" id=\"valet\" value=\"발렛파킹\" ");
      out.print( h.getHospConv() != null && h.getHospConv().contains("발렛")? "checked":"");
      out.write("/>\n");
      out.write("\t\t                    <label for=\"valet\">발렛파킹</label>\n");
      out.write("\t\t                    </fieldset>\n");
      out.write("\t\t                    \n");
      out.write("\t\t                    <fieldset>\n");
      out.write("\t\t                    <legend class=\"text-label\">진료시간</legend>\n");
      out.write("\t\t                    ");
 String[] weekDay = {"mon", "tue", "wed", "thu", "fri", "sat", "sun" };
					         String[] openTime = {"9:00","9:30","10:00","10:30","11:00","11:30","12:00","12:30","13:00","13:30","14:00"}; 
					         String[] closeTime = {"14:00","14:30","15:00","15:30","18:00","18:30","19:00","19:30","20:00","20:30","21:00"}; 
					         String[] week = {"월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일"};
					         String[] open = {ht.getMonOpen(), ht.getTueOpen(), ht.getWedOpen(), ht.getThuOpen(), ht.getFriOpen(), ht.getSatOpen(), ht.getSunOpen()};
					         String[] close = {ht.getMonEnd(), ht.getTueEnd(), ht.getWedEnd(), ht.getThuEnd(), ht.getFriEnd(), ht.getSatEnd(), ht.getSunEnd()}; 
      out.write("\n");
      out.write("\t\t\t\t\t        \n");
      out.write("\t\t\t\t\t        ");
 for(int i=0; i<7; i++) {
      out.write("\n");
      out.write("\t\t\t\t\t        \t<label for=\"");
      out.print( weekDay[i] );
      out.write('"');
      out.write('>');
      out.print( week[i] );
      out.write("</label>\n");
      out.write("\t\t\t\t\t        \t<select name=\"");
      out.print( weekDay[i] );
      out.write("-open\" id=\"\">\n");
      out.write("\t\t\t\t\t        \t\t<option value=\"\" ");
      out.print("".equals(open[i])? "selected": "" );
      out.write(">오픈시간</option>\n");
      out.write("\t\t\t\t\t        \t");
 for(int j=0; j<openTime.length; j++) {
      out.write("\n");
      out.write("\t\t\t\t\t        \t\t<option value=\"");
      out.print(openTime[j]);
      out.write('"');
      out.print(openTime[j].equals(open[i])? "selected": "" );
      out.write('>');
      out.print(openTime[j]);
      out.write("</option>\n");
      out.write("\t\t\t\t\t           \t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t           \t</select>~\n");
      out.write("\t\t\t\t\t        \t<select name=\"");
      out.print( weekDay[i] );
      out.write("-close\" id=\"\">\n");
      out.write("\t\t\t\t\t        \t\t<option value=\"\" ");
      out.print("".equals(close[i])? "selected": "" );
      out.write(">마감시간</option>\n");
      out.write("\t\t\t\t\t           \t");
 for(int k=0; k<closeTime.length; k++) {
      out.write("\n");
      out.write("\t\t\t\t\t        \t\t<option value=\"");
      out.print(closeTime[k]);
      out.write('"');
      out.print(closeTime[k].equals(close[i])? "selected": "" );
      out.write('>');
      out.print(closeTime[k]);
      out.write("</option>\n");
      out.write("\t\t\t\t\t           \t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t           \t</select><br />\n");
      out.write("\t\t\t\t\t        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("\t                   \t<label for=\"\">점심시간</label>\n");
      out.write("\t\t\t\t\t        <select name=\"lunch-open\" id=\"lunch-open\">\n");
      out.write("\t\t\t\t\t            <option value=\"\" ");
      out.print( ht.getLunOpen() == null ? "selected":"" );
      out.write(">시작</option>\n");
      out.write("\t\t\t\t\t            <option value=\"11:00\" ");
      out.print( "11:00".equals(ht.getLunOpen()) ? "selected":"" );
      out.write(">11:00</option>\n");
      out.write("\t\t\t\t\t            <option value=\"11:30\" ");
      out.print( "11:30".equals(ht.getLunOpen()) ? "selected":"" );
      out.write(">11:30</option>\n");
      out.write("\t\t\t\t\t            <option value=\"12:00\" ");
      out.print( "12:00".equals(ht.getLunOpen()) ? "selected":"" );
      out.write(">12:00</option>\n");
      out.write("\t\t\t\t\t            <option value=\"12:30\" ");
      out.print( "12:30".equals(ht.getLunOpen()) ? "selected":"" );
      out.write(">12:30</option>\n");
      out.write("\t\t\t\t\t            <option value=\"13:00\" ");
      out.print( "13:00".equals(ht.getLunOpen()) ? "selected":"" );
      out.write(">13:00</option>\n");
      out.write("\t\t\t\t\t        </select>~\n");
      out.write("\t\t\t\t\t        <select name=\"lunch-close\" id=\"lunch-close\">\n");
      out.write("\t\t\t\t\t            <option value=\"\" ");
      out.print( ht.getLunEnd() == null ? "selected":"" );
      out.write(">끝</option>\n");
      out.write("\t\t\t\t\t            <option value=\"12:00\" ");
      out.print( "12:00".equals(ht.getLunEnd()) ? "selected":"" );
      out.write(">12:00</option>\n");
      out.write("\t\t\t\t\t            <option value=\"12:30\" ");
      out.print( "12:30".equals(ht.getLunEnd()) ? "selected":"" );
      out.write(">12:30</option>\n");
      out.write("\t\t\t\t\t            <option value=\"13:00\" ");
      out.print( "13:00".equals(ht.getLunEnd()) ? "selected":"" );
      out.write(">13:00</option>\n");
      out.write("\t\t\t\t\t            <option value=\"13:30\" ");
      out.print( "13:30".equals(ht.getLunEnd()) ? "selected":"" );
      out.write(">13:30</option>\n");
      out.write("\t\t\t\t\t            <option value=\"14:00\" ");
      out.print( "14:00".equals(ht.getLunEnd()) ? "selected":"" );
      out.write(">14:00</option>\n");
      out.write("\t\t\t\t\t        </select>\n");
      out.write("\t\t\t\t\t        </fieldset>\n");
      out.write("\t\t                    <!-- <input type=\"button\" value=\"취소\" class=\"submit-btn\" onclick='javascript:history.go(-1);'> -->\n");
      out.write("\t                    \t<input type=\"submit\" value=\"수정\" class=\"submit-btn\" />\n");
      out.write("\t                    \t<input type=\"button\" value=\"탈퇴\" class=\"submit-btn\" onclick=\"deleteHospital();\"/>\n");
      out.write("\t            \t\t</form>\n");
      out.write("        \t</div>\n");
      out.write("        </article>\n");
      out.write("    </section>\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/policy\">이용약관</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/privacy\">개인정보처리방침</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/biz\">사업자정보확인</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/bbc/cs\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>\r\n");
      out.write("            상호 : (주)씨닥 | 대표 : 씨닥 | 개인정보관리책임자 : KH | 전화 : 2588-2588 | 이메일 : khm0627@naver.com\r\n");
      out.write("            <Br />주소 : 서울특별시 강남구 역삼동 | 사업자등록번호 : 110-426-375674 | 통신판매 : 제 2020-서울강남-0922호 | 호스팅제공자 : (주)씨닥\r\n");
      out.write("            <br><br>\r\n");
      out.write("            Copyrighter ⓒ 2020 SeeDoc KH-m\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
