/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-18 00:56:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.booking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import booking.model.vo.Booking;
import member.model.vo.User;
import java.util.Date;
import java.text.SimpleDateFormat;
import hospital.model.vo.Hospital;
import hospital.model.vo.HospTime;
import hospital.model.vo.HospFile;
import hospital.model.vo.HospDoctor;
import java.util.List;
import member.model.vo.User;
import hospital.model.vo.Hospital;

public final class booking_002dupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1594876536000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1594080906000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("hospital.model.vo.HospFile");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("member.model.vo.User");
    _jspx_imports_classes.add("hospital.model.vo.HospTime");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("hospital.model.vo.Hospital");
    _jspx_imports_classes.add("hospital.model.vo.HospDoctor");
    _jspx_imports_classes.add("booking.model.vo.Booking");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User user = (User)request.getAttribute("user");
	Hospital hosp = (Hospital)request.getAttribute("hosp");
	List<HospDoctor> doclist = (List<HospDoctor>)request.getAttribute("doclist");
	List<HospFile> hfList = (List<HospFile>)request.getAttribute("hflist");
	HospTime ht = (HospTime)request.getAttribute("ht");
	Booking booking = (Booking)request.getAttribute("booking");

	String birth = null;
	if("1".equals(user.getUserBirth().substring(7)) || "2".equals(user.getUserBirth().substring(7))){
		birth = "19"+ user.getUserBirth().substring(0, 6);
	} else {
		birth = "20"+ user.getUserBirth().substring(0, 6);
	}
	
	//System.out.println(birth);
	birth = birth.substring(0,4) + "-" + birth.substring(4,6) + "-" + birth.substring(6);
	//System.out.println(birth);

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	Cookie[] cookies2 = request.getCookies();
	boolean saveUserIdChecked = false;
	String saveUserIdValue = "";
	if(cookies2 != null) {
		for(Cookie c : cookies2) {
			String k = c.getName();
			String v = c.getValue();

			if("saveUserId".equals(k)) {
				saveUserIdChecked = true;
				saveUserIdValue = v;
			}
		}
	}
	
	
	
	Hospital hospLoggedIn = (Hospital)session.getAttribute("hospLoggedIn");
	//쿠키관련
	Cookie[] cookies = request.getCookies();
	boolean saveHospIdChecked = false;
	String saveHospIdValue = "";
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();

			if("saveHospId".equals(k)) {
				saveHospIdChecked = true;
				saveHospIdValue = v;
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/footer.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top-bar\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <ul>\r\n");
      out.write("                ");
if(hospLoggedIn == null && userLoggedIn == null) { 
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("                        <li style=\"color:white\">홈</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/login\">\r\n");
      out.write("                        <li>로그인</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/register\">\r\n");
      out.write("                        <li>회원가입</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">\r\n");
      out.write("                        <li>회원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/hospList\">\r\n");
      out.write("                        <li>병원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } else if(hospLoggedIn != null) { 
      out.write("\r\n");
      out.write("                \t<span class=\"login1\"><strong>");
      out.print( hospLoggedIn.getHospName() );
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/edit-info?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>병원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/doctorList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>의사보기</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingHopitalList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역(병원)</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                \t<span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit-info?userId=");
      out.print( userLoggedIn.getUserId());
      out.write("\">\r\n");
      out.write("                        <li>회원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookinglist?userId=");
      out.print( userLoggedIn.getUserId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sub-bar\"></div>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/booking-hos.css\">\r\n");
      out.write("<script src=\"../js/datepicker.js\"></script>\r\n");
      out.write("<section>\r\n");
      out.write("\t<div class=\"bk-logo-wrap\">\r\n");
      out.write("\t\t<div class=\"hos-logo\">\r\n");
      out.write("\t\t\t<h1>");
      out.print( hosp.getHospName() );
      out.write("</h1>\r\n");
      out.write("\t\t        ");
 for(HospFile hf: hfList) {
      out.write("\r\n");
      out.write("\t\t        ");
 System.out.println(hf); 
      out.write("\r\n");
      out.write("\t        \t\t");
 if("logo".equals(hf.getUse()) && hf.getBoardOriginalFileName()!=null){ 
      out.write("\r\n");
      out.write("\t        \t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/hospital/");
      out.print(hf.getBoardRenamedFileName() );
      out.write("\" alt=\"\">\r\n");
      out.write("\t\t        \t");
 } else if("logo".equals(hf.getUse()) && hf.getBoardOriginalFileName()==null){ 
      out.write("\r\n");
      out.write("\t\t        \t\t<img src=\"../img/default-logo.png\" alt=\"\" style=\"width: 200px; margin-top: 130px;\">\r\n");
      out.write("\t        \t\t");
 } 
      out.write("\r\n");
      out.write("\t        \t\t");
 if("thumbnail".equals(hf.getUse()) && hf.getBoardOriginalFileName()!=null){ 
      out.write("\r\n");
      out.write("\t        \t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/hospital/");
      out.print(hf.getBoardRenamedFileName() );
      out.write("\" alt=\"\">\r\n");
      out.write("\t\t        \t");
 } else if("thumbnail".equals(hf.getUse()) && hf.getBoardOriginalFileName()==null){ 
      out.write("\r\n");
      out.write("\t\t        \t\t<img src=\"../img/default-thumbnail.png\" alt=\"\" style=\"width: 200px; margin-top: 130px;\">\r\n");
      out.write("\t        \t\t");
 } 
      out.write("\r\n");
      out.write("        \t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"opa-back\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<h1 class=\"title\">\r\n");
      out.write("\t\t<span>●</span> 병원 의사\r\n");
      out.write("\t</h1>\r\n");
      out.write("\t<div class=\"bk-main-wrap\">\r\n");
      out.write("\t\t<div class=\"doc-wrap\">\r\n");
      out.write("\t\t\t");
 for(HospDoctor hd : doclist) {
      out.write("\r\n");
      out.write("\t\t\t<div class=\"doc-card\">\r\n");
      out.write("\t\t\t\t<div class=\"doc-img\">\r\n");
      out.write("\t\t\t\t\t");
 for(HospFile fl : hfList) {
 		            		if(fl.getDoctorNo() != null) {
                				if((fl.getDoctorNo()).equals(hd.getDoctorNo())) { 
                					if(fl.getBoardOriginalFileName() != null) { 
                				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img alt=\"의사이미지\" src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/hospital/");
      out.print(fl.getBoardRenamedFileName() );
      out.write("\">\r\n");
      out.write("                \t\t\t\t\t");
}else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img alt=\"의사이미지\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/doctor.png\">\r\n");
      out.write("                \t");
				}
				 				}
				 			}
						}
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"doc-info\">\r\n");
      out.write("\t\t\t\t\t<h1>");
      out.print( hd.getDoctorName() );
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t<p>[진료과]</p>\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print( hd.getHospDept() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t");
 if(hd.getDoctorTreat()!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<p>[진료내용]</p>\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print( hd.getDoctorTreat() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"doc-button\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"doctorNoView\" value=\"");
      out.print( hd.getDoctorNo() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"진료예약\" id=\"doctor-select\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<h1 class=\"title\">\r\n");
      out.write("\t\t<span>●</span> 예약일정\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<div class=\"bk-info-wrap\">\r\n");
      out.write("\t\t\t<table id=\"calendar\">\r\n");
      out.write("\t\t\t\t<tr class=\"cal-title\">\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t<label onclick=\"prevCalendar()\">\r\n");
      out.write("\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"7px\" height=\"11px\">\r\n");
      out.write("\t                    <path fill-rule=\"evenodd\" fill=\"rgb(55, 59, 68)\" d=\"M2.983,5.500 L6.014,8.530 C6.372,8.889 6.372,9.471 6.014,9.830 C5.655,10.188 5.073,10.188 4.715,9.830 L1.511,6.626 C1.262,6.638 1.009,6.556 0.818,6.366 C0.583,6.130 0.517,5.801 0.591,5.500 C0.517,5.198 0.583,4.869 0.818,4.634 C1.009,4.443 1.262,4.361 1.512,4.373 L4.715,1.170 C5.073,0.811 5.655,0.811 6.014,1.170 C6.372,1.529 6.372,2.110 6.014,2.469 L2.983,5.500 Z\" />\r\n");
      out.write("\t                    </svg>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"tbCalendarYM\" colspan=\"3\">yyyy년 m월</th>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" style=\"text-align: left;\">\r\n");
      out.write("\t\t\t\t\t\t<label onclick=\"nextCalendar()\"> \r\n");
      out.write("\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"7px\" height=\"11px\">\r\n");
      out.write("\t                    <path fill-rule=\"evenodd\" fill=\"rgb(55, 59, 68)\" d=\"M6.026,6.397 C5.835,6.588 5.582,6.670 5.332,6.657 L2.129,9.861 C1.770,10.219 1.188,10.219 0.830,9.861 C0.471,9.502 0.471,8.920 0.830,8.562 L3.860,5.531 L0.830,2.500 C0.471,2.142 0.471,1.560 0.830,1.201 C1.188,0.843 1.770,0.843 2.129,1.201 L5.332,4.405 C5.582,4.392 5.835,4.474 6.026,4.665 C6.261,4.900 6.326,5.230 6.252,5.531 C6.326,5.833 6.261,6.161 6.026,6.397 Z\" />\r\n");
      out.write("\t                    </svg>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th style=\"text-align: center; color: #ff5d5d;\">일</th>\r\n");
      out.write("\t\t\t\t\t<th>월</th>\r\n");
      out.write("\t\t\t\t\t<th>화</th>\r\n");
      out.write("\t\t\t\t\t<th>수</th>\r\n");
      out.write("\t\t\t\t\t<th>목</th>\r\n");
      out.write("\t\t\t\t\t<th>금</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"text-align: center; color: #427cff;\">토</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tbuildCalendar(); //\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"time-wrap\">\r\n");
      out.write("\t\t\t<h2 style=\"text-align:center\">예약시간</h2>\r\n");
      out.write("\t\t\t\t<h4 style=\"text-align: center; margin-top:150px;\">예약일을 선택해주세요.</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"bk-info\">\r\n");
      out.write("                    <div class=\"bk-title\">추가정보<span>\r\n");
      out.write("                        <img src=\"../img/check-off.png\" alt=\"\">\r\n");
      out.write("                            \t필수입력</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bk-info-main\">\r\n");
      out.write("                        \r\n");
      out.write("                        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/booking/bookingUpdate\" name=\"bookingInsertFrm\" method=\"post\">\r\n");
      out.write("                        <p class=\"item-title\"><img src=\"../img/check-on.png\" alt=\"\">생년월일</p>\r\n");
      out.write("                        <input type=\"date\" class=\"user-input check-input\" name=\"birth\" value=\"");
      out.print( birth );
      out.write("\">\r\n");
      out.write("                        <p class=\"item-title choice\"><img src=\"../img/check-on.png\" alt=\"\">연락처</p>\r\n");
      out.write("                        <input type=\"text\" name=\"phone\" value=\"");
      out.print( user.getUserPhone() );
      out.write("\" placeholder=\"연락처\">\r\n");
      out.write("                        <p class=\"item-title choice\"><img src=\"../img/s-round.png\" alt=\"\">이메일</p>\r\n");
      out.write("                        <input type=\"text\" name=\"email\" value=\"");
      out.print( user.getUserEmail() );
      out.write("\" placeholder=\"이메일\">\r\n");
      out.write("                        <p class=\"item-title choice\">\r\n");
      out.write("                            <img src=\"../img/s-round.png\" alt=\"\">증상\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <textarea name=\"sysptom\" id=\"\" cols=\"30\" rows=\"10\" placeholder=\"아픈 증상을 적어주세요\"></textarea><br />\r\n");
      out.write("                        <h3>&lt;예약안내 공지사항&gt;</h3>\r\n");
      out.write("                        <p class=\"notice\">\r\n");
      out.write("\t\t\t\t         1. 기본수집항목: [필수] 아이디, 이름, (휴대)전화번호, [선택] 이메일 주소 , 증상</p>\r\n");
      out.write("\t\t\t\t\t\t <p class=\"notice\">2. 수집 및 이용목적 : 사업자회원과 예약이용자의 원활한 거래 진행, 고객상담, 불만처리 등 민원 처리, 분쟁조정 해결을 위한 기록보존</p>\r\n");
      out.write("\t\t\t\t\t\t <p class=\"notice\">3. 보관기간 : 회원탈퇴 등 개인정보 이용목적 달성 시까지 보관</p>\r\n");
      out.write("\t\t\t\t\t\t <p class=\"notice\">4. 동의 거부권 등에 대한 고지: 정보주체는 개인정보의 수집 및 이용 동의를 거부할 권리가 있으나, 이 경우 상품 및 서비스 예약이 제한될 수 있습니다.</p>\r\n");
      out.write("                        <span id=\"check-reg\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"agree\" id=\"agree\">\r\n");
      out.write("                        <label class=\"agree-label\" for=\"agree\">이용자 약관 전체동의</label>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <!-- <span><img src=\"../img/w-check.png\" alt=\"\"> 필수입력</span><br /> -->\r\n");
      out.write("                        <input class=\"reg-btn\" type=\"button\" value=\"예약\" >\r\n");
      out.write("                        <input type=\"hidden\" name=\"userId\" value=\"");
      out.print( user.getUserId() );
      out.write("\"/>\r\n");
      out.write("                        <input type=\"hidden\" name=\"hospId\" value=\"");
      out.print( hosp.getHospId() );
      out.write("\"/>\r\n");
      out.write("                        <input type=\"hidden\" name=\"bookingNo\" value=\"");
      out.print( booking.getBookingNo() );
      out.write("\"/>\r\n");
      out.write("                        <input type=\"hidden\" name=\"doctorNo\" value=\"\"/>\r\n");
      out.write("                        <input type=\"hidden\" name=\"doctorName\" value=\"\"/>\r\n");
      out.write("                        <input type=\"hidden\" name=\"userName\" value=\"");
      out.print( user.getUserName() );
      out.write("\"/>\r\n");
      out.write("                        <input type=\"hidden\" name=\"bookingDate\" value=\"\"/>\r\n");
      out.write("                        <input type=\"hidden\" name=\"bookingTime\" id=\"bookingTime\" value=\"\"/>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\t<div class=\"modal_back\"></div>\r\n");
      out.write("    <div class=\"modal\">\r\n");
      out.write("        <h1>예약확인</h1>\r\n");
      out.write("        <p>예약자 : ");
      out.print(user.getUserId() );
      out.write("</p>\r\n");
      out.write("        <p>예약 날짜 : </p>\r\n");
      out.write("        <p>예약 시간 : </p>\r\n");
      out.write("        <p>생년월일: </p>\r\n");
      out.write("        <p>전화번호(환자): ");
      out.print( user.getUserPhone() );
      out.write("</p>\r\n");
      out.write("        <p>병원 : ");
      out.print( hosp.getHospName() );
      out.write("</p>\r\n");
      out.write("        <p>전화번호: ");
      out.print( hosp.getHospTel() );
      out.write("</p>\r\n");
      out.write("        <p>담당의사 : </p>\r\n");
      out.write("        <!-- <a href=\"../index.html\"><input type=\"button\" id=\"btn-insert\" value=\"확인\"></a> -->\r\n");
      out.write("        <input type=\"button\" id=\"btn-insert\" value=\"확인\">\r\n");
      out.write("    </div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\".time\").find(\"input\").click(function() {\r\n");
      out.write("\t\t$(\".time\").find(\"input\").css({\r\n");
      out.write("\t\t\t\"background-color\" : \"white\",\r\n");
      out.write("\t\t\t\"color\" : \"black\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(this).css({\r\n");
      out.write("\t\t\t\"background-color\" : \"#4286f4\",\r\n");
      out.write("\t\t\t\"color\" : \"white\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("$(function (){\r\n");
      out.write("\tvar doctorNo = \"\";\r\n");
      out.write("\tvar doctorName = \"\";\r\n");
      out.write("/* \tvar bookingDate = \"\"; */\r\n");
      out.write("\tvar bookingTime = \"\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t/* 의사 클릭시 의사번호, 의사이름 변수에 담기 */\r\n");
      out.write(" \t$(\".doc-button\").on('click','input:button',function() {\r\n");
      out.write("\t\t$(\"[name=doctorNo]\").attr('value', $(this).prev().val());\r\n");
      out.write("\t\t$(\"[name=doctorName]\").attr('value', $(this).parent().prev().find(\"h1\").text());\r\n");
      out.write("\t\t$(\".modal\").children().eq(8).html(\"담당의사 : \"+$(this).parent().prev().find(\"h1\").text()+\" 의사\");\r\n");
      out.write("\t\tdoctorNo = $(this).prev().val();\r\n");
      out.write("\t\tconsole.log(doctorNo);\r\n");
      out.write("/* \t\tdoctorName = $(this).parent().prev().find(\"h1\").text();\r\n");
      out.write("\t\tconsole.log(doctorName); */\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/* 달력 클릭시 예약 시간 변경 */\r\n");
      out.write("\t$(\"#calendar\").on('click','td',function() {\r\n");
      out.write("\t\t/* 의사 선택 없이 캘린더 선택시 알림 */\r\n");
      out.write("\t\tif($(\"[name=doctorNo]\").val() == \"\" && $(\"[name=doctorName]\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"진료 받을 의사를 선택해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlet year = $(\"#tbCalendarYM\").text().substr(0,$(\"#tbCalendarYM\").text().indexOf(\".\"));\r\n");
      out.write("\t\tlet mon = $(\"#tbCalendarYM\").text().substr($(\"#tbCalendarYM\").text().indexOf(\".\")+1)<10?\"0\"+$(\"#tbCalendarYM\").text().substr($(\"#tbCalendarYM\").text().indexOf(\".\")+1):$(\"#tbCalendarYM\").text().substr($(\"#tbCalendarYM\").text().indexOf(\".\")+1);\r\n");
      out.write("\t\tlet days = $(\"#calendar td.on\").text().replace(/[^0-9]/g,'');\r\n");
      out.write("\t\tlet day = days <10 ? \"0\"+days:days;\r\n");
      out.write("\t\tlet date = year+mon+day; //20200709\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlet week=new Date(year, mon-1, day);\r\n");
      out.write("\t\tlet bookingDate = year+\"-\"+mon+\"-\"+day;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//정보 확인창용\r\n");
      out.write("\t\t$(\"[name=bookingDate]\").attr('value', year+\"-\"+mon+\"-\"+day);\r\n");
      out.write("\t\t$(\".modal\").children().eq(2).html(\"예약날짜 : \"+year+\".\"+mon+\".\"+day);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//alert(week);\r\n");
      out.write("\t\t// 0:일요일, 1:월, 2:화, 3:수, 4:목, 5:금, 6:토 \r\n");
      out.write("\t\t//alert(week.getDay());\r\n");
      out.write("\t\t//let today = new Date();\r\n");
      out.write("\t \t//\tconsole.log(today.getHours());\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print( request.getContextPath() );
      out.write("/booking/bookingCalendar\",\r\n");
      out.write("\t\t\tmethod: \"Post\",\r\n");
      out.write("\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\tdata: {week:week.getDay(), year: year, mon:mon, day:day, \r\n");
      out.write("\t\t\t\thospId:\"");
      out.print( hosp.getHospId() );
      out.write("\", doctorNo:doctorNo},\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t        let today = new Date();\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        if(year == today.getFullYear() &&  mon == today.getMonth()+1 && day < today.getDate()\r\n");
      out.write("\t            \t\t|| year == today.getFullYear() &&  mon < today.getMonth()+1 \r\n");
      out.write("\t            \t\t|| year < today.getFullYear()){\r\n");
      out.write("\t\t        \t$(\".time-wrap\").html(\"<h2 style='text-align:center'>예약시간</h2><h4 style='text-align: center; margin-top:150px;'>지난 예약 일자입니다.</h4>\");\r\n");
      out.write("\t\t        \tconsole.log(data);\r\n");
      out.write("\t\t        }else{\r\n");
      out.write("\t\t\t\t\t$(\".time-wrap\").html(data);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(xhr, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax 요청 실패!\");\r\n");
      out.write("\t\t\t\tconsole.log(xhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 약관동의 */\r\n");
      out.write("\t$(\".reg-btn\").click(function () {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\tif($(\"[name=doctorNo]\").val() == \"\" && $(\"[name=doctorName]\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"진료 받을 의사를 선택해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("  \t\tif($(\"[name=bookingDate]\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"진료 받을 일정을 선택해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif($(\"[name=bookingTime]\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"진료 받을 시간을 선택해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"[name=birth]\").val() == \"\") {\r\n");
      out.write("\t\t\talert(\"생년월일을 입력해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"[name=phone]\").val() == \"\") {\r\n");
      out.write("\t\t\talert(\"핸드폰 번호를 입력해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 7/15 변경 */\r\n");
      out.write("\t\tvar regExp = /^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$/;\r\n");
      out.write("\t\tif(!regExp.test($(\"[name=phone]\").val())) {\r\n");
      out.write("\t\t\talert(\"핸드폰 번호를 다시 확인해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"[name=agree]\").is(\":checked\") == true){\r\n");
      out.write("\t\t\t$(\".modal\").children().eq(4).html(\"생년월일: \"+$(\"[name=birth]\").val());\r\n");
      out.write("\t        $(\".modal\").css(\"display\", \"block\");\r\n");
      out.write("\t        $(\".modal_back\").css(\"display\", \"block\");\t\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\talert(\"이용자 약관 동의을 확인해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t    /* 예약 확인창 확인 버튼 클릭시 submit 처리 */\r\n");
      out.write("\t\t$(\"#btn-insert\").click(function(){\r\n");
      out.write("\t\t\t$(\"[name=bookingInsertFrm]\").submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("    });\r\n");
      out.write("    $(\".modal_back\").click(function () {\r\n");
      out.write("        $(\".modal\").css(\"display\", \"none\");\r\n");
      out.write("        $(\".modal_back\").css(\"display\", \"none\");\r\n");
      out.write("    });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/policy\">이용약관</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/privacy\">개인정보처리방침</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/biz\">사업자정보확인</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/bbc/cs\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>\r\n");
      out.write("            상호 : (주)씨닥 | 대표 : 씨닥 | 개인정보관리책임자 : KH | 전화 : 2588-2588 | 이메일 : khm0627@naver.com\r\n");
      out.write("            <Br />주소 : 서울특별시 강남구 역삼동 | 사업자등록번호 : 110-426-375674 | 통신판매 : 제 2020-서울강남-0922호 | 호스팅제공자 : (주)씨닥\r\n");
      out.write("            <br><br>\r\n");
      out.write("            Copyrighter ⓒ 2020 SeeDoc KH-m\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
