/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-20 07:05:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.booking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import booking.model.vo.BookingCount;
import booking.model.vo.BookingAdd;
import java.util.List;
import member.model.service.MemberService;
import member.model.vo.User;
import hospital.model.vo.Hospital;

public final class hospital_002dbooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1595158624000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1595220082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("booking.model.vo.BookingCount");
    _jspx_imports_classes.add("member.model.vo.User");
    _jspx_imports_classes.add("hospital.model.vo.Hospital");
    _jspx_imports_classes.add("booking.model.vo.BookingAdd");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  
	List<BookingAdd> list = (List<BookingAdd>)request.getAttribute("list"); 
	BookingCount bc = (BookingCount)request.getAttribute("bc");
	String pageBar = (String)request.getAttribute("pageBar");
	String searchType = request.getParameter("searchType");
	String searchKeyword = request.getParameter("searchKeyword");
	System.out.println(searchType);

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	Cookie[] cookies2 = request.getCookies();
	boolean saveUserIdChecked = false;
	String saveUserIdValue = "";
	if(cookies2 != null) {
		for(Cookie c : cookies2) {
			String k = c.getName();
			String v = c.getValue();

			if("saveUserId".equals(k)) {
				saveUserIdChecked = true;
				saveUserIdValue = v;
			}
		}
	}
	
	
	
	Hospital hospLoggedIn = (Hospital)session.getAttribute("hospLoggedIn");
	//쿠키관련
	Cookie[] cookies = request.getCookies();
	boolean saveHospIdChecked = false;
	String saveHospIdValue = "";
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();

			if("saveHospId".equals(k)) {
				saveHospIdChecked = true;
				saveHospIdValue = v;
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>See Doctor</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/footer.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top-bar\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <ul>\r\n");
      out.write("                ");
if(hospLoggedIn == null && userLoggedIn == null) { 
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("                        <li style=\"color:white\">홈</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/login\">\r\n");
      out.write("                        <li>로그인</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/register\">\r\n");
      out.write("                        <li>회원가입</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else if(hospLoggedIn != null) { 
      out.write("\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"><span class=\"login1\"><strong>");
      out.print( hospLoggedIn.getHospName() );
      out.write("</strong></span></a>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/edit-info?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>병원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/doctorList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>의사보기</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingHopitalList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역(병원)</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                 ");
}else if(userLoggedIn!=null&&userLoggedIn.getUserRole().equals(MemberService.MEMBER_ROLE_ADMIN)){ 
      out.write("   \r\n");
      out.write("                    <span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">\r\n");
      out.write("                        <li>회원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/hospList\">\r\n");
      out.write("                        <li>병원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                \t<span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit-info?userId=");
      out.print( userLoggedIn.getUserId());
      out.write("\">\r\n");
      out.write("                        <li>회원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookinglist?userId=");
      out.print( userLoggedIn.getUserId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sub-bar\"></div>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/hospital-booking.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\tdiv#search-container {margin:20px 0 0px 0; padding:10px; background-color: white; width:100%;}\r\n");
      out.write("\tdiv#search-doctorName {");
      out.print( searchType==null ||"doctorName".equals(searchType) ? "display: inline-block;" : "display:none");
      out.write("}\r\n");
      out.write("\tdiv#search-userName{");
      out.print( "userName".equals(searchType) ? "display: inline-block;" : "display:none");
      out.write("}\r\n");
      out.write("\tdiv#search-schedule{");
      out.print( "schedule".equals(searchType) ? "display: inline-block;" : "display:none");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write(" $(function(){\r\n");
      out.write("\t$(\"#btn-total\").click(function() {\r\n");
      out.write("\t\tlet $frm = $(\"[name=bookingStateFrm]\");\r\n");
      out.write("\t\t$frm.children(\"[name=state]\").val(\"_\");\r\n");
      out.write("\t\t$frm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btn-approval\").click(function() {\r\n");
      out.write("\t\tlet $frm = $(\"[name=bookingStateFrm]\");\r\n");
      out.write("\t\t$frm.children(\"[name=state]\").val(\"A\");\r\n");
      out.write("\t\t$frm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btn-finish\").click(function() {\r\n");
      out.write("\t\tlet $frm = $(\"[name=bookingStateFrm]\");\r\n");
      out.write("\t\t$frm.children(\"[name=state]\").val(\"F\");\r\n");
      out.write("\t\t$frm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btn-cancle\").click(function() {\r\n");
      out.write("\t\tlet $frm = $(\"[name=bookingStateFrm]\");\r\n");
      out.write("\t\t$frm.children(\"[name=state]\").val(\"C\");\r\n");
      out.write("\t\t$frm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t/* 7/15 변경 */\r\n");
      out.write("\t$(\".btn-delete\").click(function () {\r\n");
      out.write("\t\tlet $tableTr = $(this).parent().parent().next();\r\n");
      out.write("\t\t//console.log($tableTr);\t\t\r\n");
      out.write("\t\tstatus = $(\"#hidden\").css(\"display\");\r\n");
      out.write("\t\tif (status == \"none\") { \r\n");
      out.write("\t\t\t$($tableTr).css(\"display\", \"\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$($tableTr).css(\"display\", \"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#searchType\").change(function() {\r\n");
      out.write("\t\t$(\"#search-doctorName, #search-userName, #search-schedule\").hide();\r\n");
      out.write("\t\t$(\"#search-\" + $(this).val()).css(\"display\",\"inline-block\");\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\t ");
 for(BookingAdd b : list) {
      out.write("\r\n");
      out.write("\tfunction updateBooking");
      out.print(b.getBookingNo() );
      out.write("(){\r\n");
      out.write("\t\tif(confirm(\"예약을 변경하시겠습니까?\")){\r\n");
      out.write("\t\t\tlet $deleteFrm = $(\"[name=updateBookingFrm");
      out.print(b.getBookingNo() );
      out.write("]\");\r\n");
      out.write("\t\t\t$deleteFrm.attr(\"action\", \"");
      out.print( request.getContextPath() );
      out.write("/booking/updateBookingFrm\");\r\n");
      out.write("\t\t\t$deleteFrm.submit();\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t/* 7/15 추가 */\r\n");
      out.write("\tfunction completeBooking");
      out.print(b.getBookingNo() );
      out.write("(){\r\n");
      out.write("\t\tif(confirm(\"회원이 병원 이용을 완료하셨습니까??\")){\r\n");
      out.write("\t\t\tlet $deleteFrm = $(\"[name=completeBookingFrm");
      out.print(b.getBookingNo() );
      out.write("]\");\r\n");
      out.write("\t\t\t$deleteFrm.attr(\"action\", \"");
      out.print( request.getContextPath() );
      out.write("/booking/completeBooking\");\r\n");
      out.write("\t\t\t$deleteFrm.submit();\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<section>\r\n");
      out.write("        <div class=\"profile-wrap\">\r\n");
      out.write("            <div class=\"profile\">\r\n");
      out.write("                <img src=\"../img/person1.png\" alt=\"\">\r\n");
      out.write("                <h1>");
      out.print( hospLoggedIn != null? hospLoggedIn.getHospName():"" );
      out.write("</h1>\r\n");
      out.write("                <p>");
      out.print( hospLoggedIn != null? hospLoggedIn.getHospId():"" );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"res-result\">\r\n");
      out.write("                <li id=\"btn-total\">\r\n");
      out.write("                    <img src=\"../img/mypage-1.png\" alt=\"\">\r\n");
      out.write("                    <p>전체</p>\r\n");
      out.write("                    <h1>");
      out.print( bc.getTotal() );
      out.write("</h1>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"btn-approval\">\r\n");
      out.write("                    <img src=\"../img/mypage-2.png\" alt=\"\" >\r\n");
      out.write("                    <p>이용예정</p>\r\n");
      out.write("                    <h1>");
      out.print( bc.getApproval() );
      out.write("</h1>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"btn-finish\">\r\n");
      out.write("                    <img src=\"../img/mypage-3.png\" alt=\"\">\r\n");
      out.write("                    <p>이용완료</p>\r\n");
      out.write("                    <h1>");
      out.print( bc.getFinish() );
      out.write("</h1>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"btn-cancle\">\r\n");
      out.write("                    <img src=\"../img/mypage-4.png\" alt=\"\">\r\n");
      out.write("                    <p>취소</p>\r\n");
      out.write("                    <h1>");
      out.print( bc.getCancle() );
      out.write("</h1>\r\n");
      out.write("                </li>\r\n");
      out.write("                <form action=\"");
      out.print( request.getContextPath() );
      out.write("/booking/bookingHopitalList\" \r\n");
      out.write("                \t\tname=\"bookingStateFrm\" method=\"get\" >\r\n");
      out.write("                \t<input type=\"hidden\" name=\"state\" />\r\n");
      out.write("                \t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print( hospLoggedIn != null ? hospLoggedIn.getHospId() : "" );
      out.write("\" />\r\n");
      out.write("                </form>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"res-wrap\">\r\n");
      out.write("            <h1><span>●</span> 병원 예약 List</h1>\r\n");
      out.write("\t            <div class=\"res-card\">\r\n");
      out.write("\t            \t<table class=\"tbl-booking\">\r\n");
      out.write("            \t\t\t<tr>\r\n");
      out.write("            \t\t\t\t<th>예약번호</th>\r\n");
      out.write("            \t\t\t\t<th>의사이름</th>\r\n");
      out.write("            \t\t\t\t<th>진료과</th>\r\n");
      out.write("            \t\t\t\t<th>환자이름</th>\r\n");
      out.write("            \t\t\t\t<th>예약날짜</th>\r\n");
      out.write("            \t\t\t\t<th>예약시간</th>\r\n");
      out.write("            \t\t\t\t<th>예약상태</th>\r\n");
      out.write("            \t\t\t\t<th>비고</th>\r\n");
      out.write("            \t\t\t</tr>\r\n");
      out.write("            ");
 if(list == null || list.isEmpty()) {
      out.write("\r\n");
      out.write("            \t<tr>\r\n");
      out.write("            \t\t<td colspan=\"8\"> <h3>조회된 예약이 없습니다.</h3></th>\r\n");
      out.write("            \t</tr>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            \t");
 for(BookingAdd b : list) { 
      out.write("\r\n");
      out.write("            \t<tr>\r\n");
      out.write("            \t\t<td>");
      out.print( b.getBookingNo() != null ? b.getBookingNo() : "" );
      out.write("</td>\r\n");
      out.write("            \t\t<td>");
      out.print( b.getDocName() != null ? b.getDocName() : "" );
      out.write("</td>\r\n");
      out.write("            \t\t<td>");
      out.print( b.getHospDept() != null ? b.getHospDept() : "" );
      out.write("</td>\r\n");
      out.write("            \t\t<td>");
      out.print( b.getUserName() != null ? b.getUserName() : "" );
      out.write("</td>\r\n");
      out.write("            \t\t<td>");
      out.print( b.getBookingDate() != null ? b.getBookingDate() : "" );
      out.write("</td>\r\n");
      out.write("            \t\t<td>");
      out.print( b.getBookingTime() != null ? b.getBookingTime() : "" );
      out.write("</td>\r\n");
      out.write("            \t\t<td>");
      out.print( b.getBookingState() != null && "A".equals(b.getBookingState())? "이용예정" : 
            			b.getBookingState() != null && "F".equals(b.getBookingState())? "이용완료" :
            			b.getBookingState() != null && "C".equals(b.getBookingState())? "예약취소" : "");
      out.write("\r\n");
      out.write("            \t\t</td>\r\n");
      out.write("            \t\t<td>\r\n");
      out.write("            \t\t\t ");
 if(userLoggedIn != null && "A".equals(userLoggedIn.getUserRole())) { 
      out.write("\r\n");
      out.write("            \t\t\t<input type=\"button\" value=\"수정\" onclick=\"updateBooking");
      out.print(b.getBookingNo() );
      out.write("();\"/>\r\n");
      out.write("            \t\t\t");
 } 
      out.write("\r\n");
      out.write("            \t\t\t");
 if(b.getBookingState() != null && "A".equals(b.getBookingState())) { 
      out.write("\r\n");
      out.write("            \t\t\t<input type=\"button\" value=\"완료\" onclick=\"completeBooking");
      out.print(b.getBookingNo() );
      out.write("();\"/>\r\n");
      out.write("\t                    <input type=\"button\" value=\"삭제\" class=\"btn-delete\" />\r\n");
      out.write("\t                    ");
 } 
      out.write("\r\n");
      out.write("            \t\t</td>\r\n");
      out.write("            \t</tr>\r\n");
      out.write("            \t<tr id=\"hidden\" style=\"display:none;\">\r\n");
      out.write("            \t\t<td colspan=\"8\" >\r\n");
      out.write("\t\t            \t<!-- 예약 수정 폼 -->\r\n");
      out.write("\t\t                <form name=\"updateBookingFrm");
      out.print(b.getBookingNo() );
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"bookingNo\" value=\"");
      out.print(b.getBookingNo() );
      out.write("\"/>\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print(b.getHospId() );
      out.write("\"/>\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"userId\" value=\"");
      out.print(b.getUserId() );
      out.write("\"/>\r\n");
      out.write("\t\t                </form>\r\n");
      out.write("\t\t                <!-- 7/15 추가 -->\r\n");
      out.write("\t\t            \t<!-- 예약 이용완료 폼 -->\r\n");
      out.write("\t\t                <form name=\"completeBookingFrm");
      out.print(b.getBookingNo() );
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"bookingNo\" value=\"");
      out.print(b.getBookingNo() );
      out.write("\"/>\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"bookingState\" value=\"F\"/>\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print( b.getHospId() );
      out.write("\"/>\r\n");
      out.write("\t\t                </form>\r\n");
      out.write("\t\t                <!-- 예약 삭제 폼 -->\r\n");
      out.write("\t\t                <form name=\"deleteBookingFrm");
      out.print(b.getBookingNo() );
      out.write("\" action=\"");
      out.print( request.getContextPath() );
      out.write("/booking/deleteHospBooking\" method=\"post\">\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"bookingNo\" value=\"");
      out.print(b.getBookingNo() );
      out.write("\"/>\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"bookingState\" value=\"C\"/>\r\n");
      out.write("\t\t                \t<textarea name='bookingCancle' placeholder='취소사유를 적어주세요' cols=100 rows=2></textarea>\r\n");
      out.write("\t\t                \t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print( b.getHospId() );
      out.write("\"/>\r\n");
      out.write("\t\t                \t<button type='submit' class='btn-insert2'>삭제</button>\r\n");
      out.write("\t\t                </form>\r\n");
      out.write("            \t\t</td>\r\n");
      out.write("            \t</tr>\r\n");
      out.write("            \t");
 } 
      out.write("\r\n");
      out.write("\t        ");
 } 
      out.write("\t\r\n");
      out.write("\t            \t</table>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"paging\">\r\n");
      out.write("                ");
      out.print( pageBar );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t    <div id=\"search-container\">\r\n");
      out.write("\t\t\t검색타입 : \r\n");
      out.write("\t\t\t<select id=\"searchType\">\r\n");
      out.write("\t\t\t\t<option value=\"doctorName\"");
      out.print( "doctorName".equals(searchType) ? "selected" : "");
      out.write(">의사이름</option>\t\t\r\n");
      out.write("\t\t\t\t<option value=\"userName\"");
      out.print( "userName".equals(searchType) ? "selected" : "");
      out.write(">회원이름</option>\r\n");
      out.write("\t\t\t\t<option value=\"schedule\"");
      out.print( "schedule".equals(searchType) ? "selected" : "");
      out.write(">일자</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<div id=\"search-doctorName\">\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingFinder\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"searchType\" value=\"doctorName\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print( hospLoggedIn!=null?hospLoggedIn.getHospId():"" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"search\" name=\"searchKeyword\"  size=\"25\" placeholder=\"검색할 의사 이름을 입력하세요.\" \r\n");
      out.write("\t\t\t\t\t\tvalue=");
      out.print( "doctorName".equals(searchType) ? searchKeyword : "");
      out.write(">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\">검색</button>\t\t\t\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"search-userName\">\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingFinder\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"searchType\" value=\"userName\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print( hospLoggedIn!=null?hospLoggedIn.getHospId():"" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"search\" name=\"searchKeyword\" size=\"25\" placeholder=\"검색할 환자 이름을 입력하세요.\"\r\n");
      out.write("\t\t\t\t\t\tvalue=");
      out.print( "userName".equals(searchType) ? searchKeyword : "");
      out.write(">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\">검색</button>\t\t\t\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"search-schedule\">\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingFinder\">\r\n");
      out.write("\t\t\t    \t<input type=\"hidden\" name=\"searchType\" value=\"schedule\"/>\r\n");
      out.write("\t\t\t    \t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print( hospLoggedIn!=null?hospLoggedIn.getHospId():"" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" name=\"searchKeyword\" size=\"25\" \r\n");
      out.write("\t\t\t\t\t\tvalue=");
      out.print( "schedule".equals(searchType) ? searchKeyword : "");
      out.write(">\r\n");
      out.write("\t\t\t    \t<button type=\"submit\">검색</button>\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/policy\">이용약관</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/privacy\">개인정보처리방침</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/biz\">사업자정보확인</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/bbc/cs\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>\r\n");
      out.write("            상호 : (주)씨닥 | 대표 : 씨닥 | 개인정보관리책임자 : KH | 전화 : 2588-2588 | 이메일 : khm0627@naver.com\r\n");
      out.write("            <Br />주소 : 서울특별시 강남구 역삼동 | 사업자등록번호 : 110-426-375674 | 통신판매 : 제 2020-서울강남-0922호 | 호스팅제공자 : (주)씨닥\r\n");
      out.write("            <br><br>\r\n");
      out.write("            Copyrighter ⓒ 2020 SeeDoc KH-m\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
