/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-20 12:39:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.booking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import booking.model.vo.BookingCount;
import booking.model.vo.BookingAdd;
import booking.model.vo.Booking;
import java.util.List;
import member.model.service.MemberService;
import member.model.vo.User;
import hospital.model.vo.Hospital;

public final class myBooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1595158624000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1595220082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("booking.model.vo.BookingCount");
    _jspx_imports_classes.add("member.model.vo.User");
    _jspx_imports_classes.add("hospital.model.vo.Hospital");
    _jspx_imports_classes.add("booking.model.vo.BookingAdd");
    _jspx_imports_classes.add("booking.model.vo.Booking");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 List<BookingAdd> list = (List<BookingAdd>)request.getAttribute("list"); 
	BookingCount bc = (BookingCount)request.getAttribute("bc");
	User user = (User)request.getAttribute("user");
	String pageBar = (String)request.getAttribute("pageBar");
	//System.out.print("jsp"+user);

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	Cookie[] cookies2 = request.getCookies();
	boolean saveUserIdChecked = false;
	String saveUserIdValue = "";
	if(cookies2 != null) {
		for(Cookie c : cookies2) {
			String k = c.getName();
			String v = c.getValue();

			if("saveUserId".equals(k)) {
				saveUserIdChecked = true;
				saveUserIdValue = v;
			}
		}
	}
	
	
	
	Hospital hospLoggedIn = (Hospital)session.getAttribute("hospLoggedIn");
	//쿠키관련
	Cookie[] cookies = request.getCookies();
	boolean saveHospIdChecked = false;
	String saveHospIdValue = "";
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();

			if("saveHospId".equals(k)) {
				saveHospIdChecked = true;
				saveHospIdValue = v;
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>See Doctor</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/footer.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top-bar\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <ul>\r\n");
      out.write("                ");
if(hospLoggedIn == null && userLoggedIn == null) { 
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("                        <li style=\"color:white\">홈</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/login\">\r\n");
      out.write("                        <li>로그인</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/register\">\r\n");
      out.write("                        <li>회원가입</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else if(hospLoggedIn != null) { 
      out.write("\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/hospital?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"><span class=\"login1\"><strong>");
      out.print( hospLoggedIn.getHospName() );
      out.write("</strong></span></a>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/edit-info?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>병원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/hospital/doctorList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\">\r\n");
      out.write("                        <li>의사보기</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookingHopitalList?hospId=");
      out.print( hospLoggedIn.getHospId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역(병원)</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                 ");
}else if(userLoggedIn!=null&&userLoggedIn.getUserRole().equals(MemberService.MEMBER_ROLE_ADMIN)){ 
      out.write("   \r\n");
      out.write("                    <span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">\r\n");
      out.write("                        <li>회원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/hospList\">\r\n");
      out.write("                        <li>병원조회</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                \t<span class=\"login1\"><strong>");
      out.print( userLoggedIn.getUserName());
      out.write("</strong></span>\r\n");
      out.write("                \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">\r\n");
      out.write("                \t\t<li>로그아웃</li>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit-info?userId=");
      out.print( userLoggedIn.getUserId());
      out.write("\">\r\n");
      out.write("                        <li>회원정보수정</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- 2/15 -->\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/booking/bookinglist?userId=");
      out.print( userLoggedIn.getUserId() );
      out.write("\"> <!-- ts -->\r\n");
      out.write("                        <li>예약내역</li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sub-bar\"></div>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/myBooking.css\">\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#btn-total\").click(function() {\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/booking/bookinglist?userId=");
      out.print( user.getUserId() );
      out.write("\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btn-approval\").click(function() {\r\n");
      out.write("\t\tlet $frm = $(\"[name=bookingStateFrm]\");\r\n");
      out.write("\t\t$frm.children(\"[name=state]\").val(\"A\");\r\n");
      out.write("\t\t$frm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btn-finish\").click(function() {\r\n");
      out.write("\t\tlet $frm = $(\"[name=bookingStateFrm]\");\r\n");
      out.write("\t\t$frm.children(\"[name=state]\").val(\"F\");\r\n");
      out.write("\t\t$frm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btn-cancle\").click(function() {\r\n");
      out.write("\t\tlet $frm = $(\"[name=bookingStateFrm]\");\r\n");
      out.write("\t\t$frm.children(\"[name=state]\").val(\"C\");\r\n");
      out.write("\t\t$frm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* hospital review  */\r\n");
      out.write("\tlet rank = document.getElementById(\"rank-wrap\").childNodes;\r\n");
      out.write("\tlet star = document.getElementById(\"star\");\r\n");
      out.write("\tlet point = document.getElementById(\"point\");\r\n");
      out.write("\tlet value = document.getElementsByName(\"reviewRank\");\r\n");
      out.write("\tlet text = document.getElementById(\"text\");\r\n");
      out.write("\tlet $rank = $(\"input[name=reviewRank]\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".review-btn\").click(function() {\r\n");
      out.write("\t\t$(\"#bookingNo\").val($(this).parent().find(\"[name=bookingNo]\").val());\r\n");
      out.write("\t\t$(\"#userId\").val($(this).parent().find(\"[name=userId]\").val());\r\n");
      out.write("\t\t$(\"#hospId\").val($(this).parent().find(\"[name=hospId]\").val());\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\trank[1].onclick = function(){\r\n");
      out.write("\t\tstar.style.width = \"23%\";\r\n");
      out.write("\t\t$rank.val('1');\r\n");
      out.write("\t\tpoint.innerHTML= \"1점\";\r\n");
      out.write("\t\ttext.innerHTML = \"최악입니다\";\r\n");
      out.write("\t}\r\n");
      out.write("\trank[2].onclick = function(){\r\n");
      out.write("\t\tstar.style.width = \"42%\";\r\n");
      out.write("\t\t$rank.val('2');\r\n");
      out.write("\t\tpoint.innerHTML= \"2점\";\r\n");
      out.write("\t\ttext.innerHTML = \"별로에요\";\r\n");
      out.write("\t}\r\n");
      out.write("\trank[3].onclick = function(){\r\n");
      out.write("\t\tstar.style.width = \"60%\";\r\n");
      out.write("\t\t$rank.val('3');\r\n");
      out.write("\t\tpoint.innerHTML= \"3점\";\r\n");
      out.write("\t\ttext.innerHTML = \"괜찮아요\";\r\n");
      out.write("\t}\r\n");
      out.write("\trank[4].onclick = function(){\r\n");
      out.write("\t\tstar.style.width = \"79%\";\r\n");
      out.write("\t\t$rank.val('4');\r\n");
      out.write("\t\tpoint.innerHTML= \"4점\";\r\n");
      out.write("\t\ttext.innerHTML = \"만족합니다\";\r\n");
      out.write("\t}\r\n");
      out.write("\trank[5].onclick = function(){\r\n");
      out.write("\t\tstar.style.width = \"100%\";\r\n");
      out.write("\t\t$rank.val('5');\r\n");
      out.write("\t\tpoint.innerHTML= \"5점\";\r\n");
      out.write("\t\ttext.innerHTML = \"최고에요\";\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#reviewCon').keyup(function (e){\r\n");
      out.write("\t\tvar content = $(this).val();\r\n");
      out.write("        $('#counter').html(content.length + '/300자');\r\n");
      out.write("        if(content.length>300){\r\n");
      out.write("    \t\talert(\"300자 제한입니다.\");\r\n");
      out.write("        \t$(this).val($(this).val().substr(0, 300));\r\n");
      out.write("        \t$('#counter').html(300 + '/300자');\r\n");
      out.write("        \t$('#counter').css(\"color\",\"black\");\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("      $('#reviewCon').keyup();\r\n");
      out.write("      \r\n");
      out.write("    $(\".review-btn\").click(function () {\r\n");
      out.write("        $(\".modal_back\").css(\"display\", \"block\");\r\n");
      out.write("        $(\".review-wrap\").css(\"display\", \"block\");\r\n");
      out.write("    });\r\n");
      out.write("    $(\".modal_back\").click(function () {\r\n");
      out.write("        $(\".modal_back\").css(\"display\", \"none\");\r\n");
      out.write("        $(\".review-wrap\").css(\"display\", \"none\");\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\t");
 for(BookingAdd b : list) {
      out.write("\r\n");
      out.write("\tfunction deleteBooking");
      out.print(b.getBookingNo() );
      out.write("(){\r\n");
      out.write("\t\tif(confirm(\"예약을 취소하시겠습니까?\")){\r\n");
      out.write("\t\t\tlet $deleteFrm = $(\"[name=deleteBookingFrm");
      out.print(b.getBookingNo() );
      out.write("]\");\r\n");
      out.write("\t\t\t$deleteFrm.attr(\"action\", \"");
      out.print( request.getContextPath() );
      out.write("/booking/deleteBooking?userId=");
      out.print( user.getUserId() );
      out.write("\");\r\n");
      out.write("\t\t\t$deleteFrm.submit();\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
 for(BookingAdd b : list) {
      out.write("\r\n");
      out.write("\tfunction updateBooking");
      out.print(b.getBookingNo() );
      out.write("(){\r\n");
      out.write("\t\tif(confirm(\"예약을 변경하시겠습니까?\")){\r\n");
      out.write("\t\t\tlet $deleteFrm = $(\"[name=updateBookingFrm");
      out.print(b.getBookingNo() );
      out.write("]\");\r\n");
      out.write("\t\t\t$deleteFrm.attr(\"action\", \"");
      out.print( request.getContextPath() );
      out.write("/booking/updateBookingFrm\");\r\n");
      out.write("\t\t\t$deleteFrm.submit();\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\tfunction writeReview(){\t\r\n");
      out.write("\t\tlet url = \"");
      out.print( request.getContextPath() );
      out.write("/board/writeReview\";\r\n");
      out.write("\t\tlet title = \"updatePasswordPopup\";\r\n");
      out.write("\t\tlet spec = \"left=500px, top=200px, width=500px, height=530px\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\topen(url, title, spec);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<section>\r\n");
      out.write("        <div class=\"profile-wrap\">\r\n");
      out.write("            <div class=\"profile\">\r\n");
      out.write("                <img src=\"../img/person1.png\" alt=\"\">\r\n");
      out.write("                <h1>");
      out.print( user.getUserName() );
      out.write("님</h1>\r\n");
      out.write("                <p>");
      out.print( user.getUserId() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"res-result\">\r\n");
      out.write("                <li id=\"btn-total\">\r\n");
      out.write("                    <img src=\"../img/mypage-1.png\" alt=\"\">\r\n");
      out.write("                    <p>전체</p>\r\n");
      out.write("                    <h1>");
      out.print( bc.getTotal() );
      out.write("</h1>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"btn-approval\">\r\n");
      out.write("                    <img src=\"../img/mypage-2.png\" alt=\"\" >\r\n");
      out.write("                    <p>이용예정</p>\r\n");
      out.write("                    <h1>");
      out.print( bc.getApproval() );
      out.write("</h1>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"btn-finish\">\r\n");
      out.write("                    <img src=\"../img/mypage-3.png\" alt=\"\">\r\n");
      out.write("                    <p>이용완료</p>\r\n");
      out.write("                    <h1>");
      out.print( bc.getFinish() );
      out.write("</h1>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"btn-cancle\">\r\n");
      out.write("                    <img src=\"../img/mypage-4.png\" alt=\"\">\r\n");
      out.write("                    <p>취소</p>\r\n");
      out.write("                    <h1>");
      out.print( bc.getCancle() );
      out.write("</h1>\r\n");
      out.write("                </li>\r\n");
      out.write("                <form action=\"");
      out.print( request.getContextPath() );
      out.write("/booking/bookingListApproval\" \r\n");
      out.write("                \t\tname=\"bookingStateFrm\" method=\"get\" >\r\n");
      out.write("                \t<input type=\"hidden\" name=\"userId\" value=\"");
      out.print( user.getUserId() );
      out.write("\"/>\r\n");
      out.write("                \t<input type=\"hidden\" name=\"state\" />\r\n");
      out.write("                </form>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"res-wrap\">\r\n");
      out.write("            <h1><span>●</span> 내 예약</h1>\r\n");
      out.write("            ");
 if(list == null || list.isEmpty()) {
      out.write("\r\n");
      out.write("            \t<div class=\"res-card\" style=\"text-align:center\">\r\n");
      out.write("            \t\t<h3>조회된 예약이 없습니다.</h3>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            \t");
 for(BookingAdd b : list) { 
      out.write("\r\n");
      out.write("\t            <div class=\"res-card\">\r\n");
      out.write("\t                <div class=\"res-type\">\r\n");
      out.write("\t                    <img src=\"../img/mypage-3.png\" alt=\"\">\r\n");
      out.write("\t                    <p>");
      out.print( "A".equals(b.getBookingState())?"이용예정":"F".equals(b.getBookingState())?"이용완료":"취소" );
      out.write("</p>\r\n");
      out.write("\t                    ");
 if("A".equals(b.getBookingState())) {
      out.write("\r\n");
      out.write("\t                    <input type=\"button\" value=\"수정\" onclick=\"updateBooking");
      out.print(b.getBookingNo() );
      out.write("();\"/>\r\n");
      out.write("\t                    <input type=\"button\" value=\"삭제\" onclick=\"deleteBooking");
      out.print(b.getBookingNo() );
      out.write("();\"/>\r\n");
      out.write("\t                    ");
 } else if("F".equals(b.getBookingState())){ 
      out.write("\r\n");
      out.write("\t                    <input type=\"button\" value=\"리뷰작성\" class=\"review-btn\"/>\r\n");
      out.write("\t                    ");
 }
      out.write("\r\n");
      out.write("\t                    <!-- 예약 수정 폼 -->\r\n");
      out.write("\t                    <form name=\"updateBookingFrm");
      out.print(b.getBookingNo() );
      out.write("\" method=\"post\">\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"bookingNo\" value=\"");
      out.print(b.getBookingNo() );
      out.write("\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"hospId\" value=\"");
      out.print(b.getHospId() );
      out.write("\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"userId\" value=\"");
      out.print(b.getUserId() );
      out.write("\"/>\r\n");
      out.write("\t                    </form>\r\n");
      out.write("\t                    <!-- 예약 삭제 폼 -->\r\n");
      out.write("\t                    <form name=\"deleteBookingFrm");
      out.print(b.getBookingNo() );
      out.write("\" method=\"post\">\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"bookingNo\" value=\"");
      out.print(b.getBookingNo() );
      out.write("\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"state\" value=\"C\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"userId\" value=\"");
      out.print(b.getUserId() );
      out.write("\"/>\r\n");
      out.write("\t                    </form>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"res-main\">\r\n");
      out.write("\t                    <p class=\"res-no\">No.");
      out.print(b.getBookingNo() );
      out.write("</p>\r\n");
      out.write("\t                    <h1>");
      out.print( b.getHospName() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( b.getDocName() );
      out.write(" 의사</h1>\r\n");
      out.write("\t                    <p>일정 : ");
      out.print( b.getBookingDate() );
      out.write(' ');
      out.print( b.getBookingTime() );
      out.write("</p>\r\n");
      out.write("\t                    <p>진료 : ");
      out.print( b.getHospDept() );
      out.write("</p>\r\n");
      out.write("\t                    ");
 if((b.getBookingState() != null && "C".equals(b.getBookingState()))
	                    		&& b.getBookingCancel() != null) {
      out.write("\r\n");
      out.write("\t                    <p>취소사유: ");
      out.print(b.getBookingCancel() );
      out.write("</p>\r\n");
      out.write("\t                    ");
 } 
      out.write("\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            \r\n");
      out.write("\t            \r\n");
      out.write("\t            ");
 } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <div class=\"paging\">\r\n");
      out.write("                ");
      out.print( pageBar );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <div class=\"modal_back\"></div>\r\n");
      out.write("    <!-- 예약 리뷰 폼 -->\r\n");
      out.write("\t<div class=\"review-wrap\">\r\n");
      out.write("                <div class=\"review-top\">리뷰작성하기</div>\r\n");
      out.write("\t<p class=\"title\">진료는 만족하셨나요?</p>\r\n");
      out.write("\t\t<!-- 댓글 작성폼 -->\r\n");
      out.write("\t\t<div class=\"review\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/writeReview\"\r\n");
      out.write("\t\t\t\tmethod=\"post\" name=\"writeReviewFrm\">\r\n");
      out.write("\t\t\t\t<span class=\"bg\"> <em id=\"star\" class=\"value\"></em></span>\r\n");
      out.write("\t\t\t\t<div id=\"rank-wrap\">\r\n");
      out.write("\t\t\t\t\t<a id=\"1\"></a><a id=\"2\"></a><a id=\"3\"></a><a id=\"4\"></a><a id=\"5\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<p class=\"point-text\"><span id=\"point\">5점</span>&nbsp;(<span id=\"text\">최고에요</span>)</p>\r\n");
      out.write("\t\t\t\t<p class=\"review-text\">어떤 점이 리뷰를 작성하게 했나요?</p>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"reviewRank\" value=\"5\" /> \r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"reviewWriter\" value=\"hong\" /> \r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"reviewLevel\" value=\"1\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"reviewRef\" value=\"0\" />\r\n");
      out.write("\t\t\t\t<textarea name=\"reviewCon\" id=\"reviewCon\" cols=\"60\" rows=\"10\"></textarea>\r\n");
      out.write("\t\t\t\t<span id=\"counter\">###</span>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"bookingNo\" id=\"bookingNo\" value=\"\"/>\r\n");
      out.write("                <input type=\"hidden\" name=\"hospId\" id=\"hospId\" value=\"\"/>\r\n");
      out.write("                <input type=\"hidden\" name=\"userId\" id=\"userId\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"등록\" id=\"write-btn\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/policy\">이용약관</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/privacy\">개인정보처리방침</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/docs/biz\">사업자정보확인</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/bbc/cs\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>\r\n");
      out.write("            상호 : (주)씨닥 | 대표 : 씨닥 | 개인정보관리책임자 : KH | 전화 : 2588-2588 | 이메일 : khm0627@naver.com\r\n");
      out.write("            <Br />주소 : 서울특별시 강남구 역삼동 | 사업자등록번호 : 110-426-375674 | 통신판매 : 제 2020-서울강남-0922호 | 호스팅제공자 : (주)씨닥\r\n");
      out.write("            <br><br>\r\n");
      out.write("            Copyrighter ⓒ 2020 SeeDoc KH-m\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
