--게시판 글 30개 / 병원 계정 정해지면 계정 넣을것
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'질 좋은 낮잠을 자기 위해 커피를 마셔라','admin','일본에서 발표한 한 연구에 따르면 일반적인 낮잠보다 ‘커피 낮잠’을 취한 사람들이 두뇌 활동에서 더 나은 결과를 보였다고 한다. 여기서 말하는 커피 낮잠이란 200mg 정도의 카페인을 소비하고 즉시 20분 정도의 낮잠을 자는 것이다. 왜 이런 결과가 나왔을까. 뉴욕의 신경전문의학박사 엘렌 토피는 두뇌 활동의 부산물인 ‘아데노신(Adenosine)’이라는 물질에 대해 언급하며 이 결과를 설명했다. 그는 “아데노신은 사람을 깨워주고 활동적으로 만들어 준다”며 “아데노신 수치가 올라가면 우리는 쉽게 피곤해진다. 그러나 낮잠은 아데노신을 없애 주고, 카페인은 아데노신을 막는 역할을 해 피로를 쉽게 사라지게 한다”고 밝혔다.','test.txt','2020062515006_12313.txt',to_date('19/02/02','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'건강한 치아를 위해서는 식후 바로 양치를 하지 마라','hospital1','스포츠 음료나 탄산 음료, 토마토 그리고 감귤류 과일 등 산이 포함된 음식은 치아의 법랑질을 녹인다. 미국 치과의학회 전 회장이었던 하워드 갬블은 “식후 바로 양치를 하면 산이 치아에 미치는 영향이 보다 빨라진다”며 “식후 30분에서 1시간 가량 후에 양치하는 것이 가장 좋다”고 제안했다.',null,null,to_date('19/02/10','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'더 날씬해지기 위해 몸무게를 늘려라','hospital1','같은 몸무게를 가진 두 사람의 체형이 현저히 다른 경우가 있다. 이는 근육량의 문제다. 같은 무게의 지방과 근육이라도 근육의 부피가 훨씬 적게 들기 때문이다. 사코 스포츠의 헬스 트레이너 마크 너팅은 “살을 뺄 때 체중이 줄어드는 것만이 능사가 아니다”며 “운동량을 늘려 근육을 만드는 것이 가장 급선무다. 이후 살을 빼면 훨씬 빠른 시간에 탄탄한 몸을 가질 수 있다”고 말했다.',null,null,to_date('19/04/05','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'적게 먹기 위해 많이 먹어라','hos1','열량이 100kcal 정도인 과자 한 봉지를 식사 대신 먹는 건 다이어트에 도움이 되는 것처럼 보인다. 그러나 이는 오히려 다이어트에 방해가 될 수 있다. 텍사스의 건강의학 전문가 에이미 굿슨은 “소량의 탄수화물을 잠깐 섭취하면 체내 혈당을 증가시켜 더 많은 탄수화물을 원하게 만든다”며 “100kcal의 과자 한 봉지가 열량이 낮다고 한 끼로 섭취했다가 자신도 모르는 사이 폭식을 할 수 있다”고 말했다. 그는 과자 한 봉지보다는 땅콩버터나 스트링 치즈를 사과와 같이 먹을 것을 제안했다. “물론 과자보다는 열량이 높을 수 있지만, 땅콩버터나 스트링 치즈에는 단백질이 풍부하게 들어 있고 사과에는 식이섬유가 들어 있어 훨씬 오랜 시간 포만감을 줄 수 있다”며 “결과적으로 그날 하루 동안은 더 적은 열량을 섭취하게 될 것”이라고 말했다.',null,null,to_date('19/04/13','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'피곤하다고 해도 에너지 드링크를 마시지 마라','hos1','에너지 드링크는 커피의 5배에 달하는 카페인을 함유하고 있다. 이는 잠시 동안 기운을 북돋아 줄 수 있으나 곧 긴장감과 함께 극심한 피로, 비정상적인 심장박동을 불러올 수 있다.',null,null,to_date('19/07/15','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'부었을 때 물을 더 많이 마셔라','hospital1','얼굴이나 몸이 부었다고 느낄 때 물을 마시면 상황이 더 악화된다고 알려져 있지만 사실 물은 붓기 완화에 도움이 된다. 캘리포니아 오렌지 카운티의 내과의사 제임스 리는 “물은 우리가 섭취한 섬유질과 결합해 젤 형태로 변하고, 이는 소화가 잘 되도록 신체 내부에 영향을 줘 붓기를 가라앉힌다”고 밝혔다. 많은 물을 마시는 것은 항산화에도 도움이 된다. 리 박사는 이에 대해 “신체의 불필요한 독소들을 내보내주기 때문”이라고 밝혔다.',null,null,to_date('19/07/20','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'다이어트 음료를 마시지 마라','hospital3','만약 정말 건강해지고 싶다면 다이어트 음료를 포함한 모든 탄산 음료를 끊어라. 존스 홉킨스 의대에서 실행한 연구에 따르면 과체중이나 비만인 사람들은 다이어트 음료를 마실 경우 일반 탄산음료를 마시는 사람들에 비해 더 많은 열량을 섭취하게 된다. 이는 위에서 언급한 바와 같이 적은 탄수화물을 섭취하면 신체가 더 많은 탄수화물을 원하게 되기 때문이다. 굿슨은 “사실 ‘0 칼로리’가 아니라 ‘적은 칼로리’가 맞는 표현이다”며 “첨가된 감미료는 어느 정도의 칼로리를 포함하고 있다. 다만 양이 적어 기재하지 않아도 될 뿐”이라고 말했다.',null,null,to_date('19/08/10','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'덥다면 뜨거운 차를 마셔라','hos1','여름 날 오후, 몸을 시원하게 만들어주기 위해 보통 사람들은 차가운 커피를 마신다. 그러나 인도나 중동의 경우, 더운 날씨에도 사람들은 뜨거운 차를 마신다. 이유가 뭘까. 한 연구에 따르면 한 모금씩 뜨거운 차를 홀짝거리며 마실 경우 신체는 체온의 변화를 감지해 땀을 배출하기 시작한다. 때문에 차를 다 마시고 나면 자연적으로 체온이 내려간다. 뜨거운 차를 마시고 난 뒤 시원함을 느끼게 되는 것은 이런 이유다.',null,null,to_date('19/08/10','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'피곤할수록 운동을 하라','hos1','길고 지겨운 업무가 끝난 뒤라면 누구라도 운동을 망설이게 된다. 하루 종일 앉아 있었음에도 피곤함이 느껴기지 때문이다. 그러나 운동 후 흘리는 땀은 오히려 기운을 북돋아 줄 수 있다. 미국의 약학 저널 ‘메디신 사이언스(Medicine Science)’에 발표된 연구에 따르면 감정적으로 느껴지는 피로의 경우 육체적인 피로를 통해 해소가 가능하다. 너팅은 “운동을 하는 것은 신체적으로는 피로할 지 몰라도 감정적으로는 훨씬 당신을 편안하게 만들어 줄 수 있다',null,null,to_date('19/08/10','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'음식은 10번이라도 십고 삼켜라','hospital2','의사들이 말하는 것처럼 30번씩 십어 넘기려다 세 숟가락 넘기기 전에  포기하지 말고, 10번이라도 꼭꼭 십어서 삼킨다. 고기를 먹으면 10번이  모자라겠지만 라면을 먹을 때도 10번은 십어야 위에서 자연스럽게 소화시킬 수 있다.',null,null,to_date('20/02/20','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'매일 조금씩 공부를 한다','hos1','두뇌는 정밀한 기계와 같아서 쓰지 않고 내버려두면 점점 더 빨리 낡는다.  공과금 계산을 꼭 암산으로 한다든가 전화번호를 하나씩 외우는 식으로 머리 쓰는  습관을 들인다. 일상에서 끝없이 머리를 써야 머리가‘녹’이 스는 것을 막을 수있다.',null,null,to_date('20/03/11','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'아침에 일어나면 기지개를 켜라','hos1','아침에 눈을 뜨면 스트레칭을 한다. 기지개는 잠으로 느슨해진 근육과 신경을 자극해 혈액순환을 도와주고 기분을 맑게 한다. 침대에서 벌떡 일어나는 습관은 나이가 들면서 혈관이 갑자기 막히는 치명적인 결과를 낳을 수도 있다.',null,null,to_date('20/03/12','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'매일 15분 씩 낮잠을 자라','hos1','피로는 쌓인 즉시 풀어야지 조금씩 쌓아 두면 병이 된다. 눈이 감기면 그 때 몸이 피곤하다는얘기. 억지로 잠을 쫓지 말고 잠깐이라도 눈을 붙인다. 15분간의 낮잠으로도 오전 중에 쌓인 피로를 말끔히 풀고 오후를 활기차게 보낼 수 있다.',null,null,to_date('20/03/13','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'아침 식사를 하고 나서 화장실을 가라','hospital1','현대인의 불치병, 특히 주부들의 고민 거리인 변비를 고치려면 아침 식사 후 무조건 화장실에 간다. 화장실로 오라는 ‘신호’가 없더라도 잠깐 앉아서 배를 마사지 하면서 3분 정도 기다리다가 나온다. 아침에 화장실에 가서 앉아 있는 버릇을 들이면 한번 배변 습관은 자연스럽게 따라온다.',null,null,to_date('20/03/14','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'식사 3~4시간 후 간식을 먹어라','hos1','조금씩 자주 먹는 것은 장수로 가는 지름길이다.  점심 식사후 속이 출출할 즈음이면 과일이나 가벼운 간식거리로 속을 채워 준다. 속이 완전히 비면 저녁에 폭식을 해 위에 부담이 된다. 그러나 점심을 배부르게  먹고, 오후에 배가 고프지 않은데도 또 먹으라는 것이 아니다. 그것은 비만으로  가는 지름길 일 뿐. 매 끼마다 한 숟가락만 더 먹고 싶을 때 수저를 놓는 습관을  들인다.',null,null,to_date('20/03/15','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'오른쪽 옆으로 누워 무릎을 구부리고 자라','hos1','세상에서 가장 편안한 자세는 아이가 엄마 뱃속에 들어 있을 때, 그 자세다. 심장에 무리를 주지 않도록 오른쪽으로 돌아누워 무릎을 약간 구부리는 자세로 있으면 가장 빨리 숙면에 빠질 수 있고 자는 중에 혈액 순환에도 도움이 된다.','test.txt','2020062515006_12313.txt',to_date('20/04/10','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'"괄약근 조이기" 체조를 한다','hos1','"괄약근 조이기"는 수많은 사람들이 있는 곳에서도 아무도 모르게 할 수 있는 건강 체조다. 출산 후 몸조리를 할 때나 갱년기 이후 요실금이 걱정될 때 이보다  더 좋은 운동은 없다. 바르게 서서 괄약근을 힘껏 조였다가 3초를 쉬고 풀어주는 동작을 반복한다.',null,null,to_date('20/04/11','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'하루에 10분 씩 노래를 부른다','hos1','스트레스를 많이 받거나 머리가 복잡할 때는 좋아하는 노래를 부른다.  듣지만 말고 큰소리로든 작은 흥얼거림이든 꼭 따라 부른다. 노래 부르기는 기분을 상쾌하게 하고 대인 기피나 우울증 치료에도 효과가 있어  정신과 치료에도 쓰이는 방법이다. 평소 설거지를 하거나 빨래를 개면서 노래를  흥얼거리는 습관은 마음을 젊고 건강하게 한다.',null,null,to_date('20/04/13','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'샤워를 하고 나서 물기를 닦지 말아라','hos1','피부도 숨을 쉴 시간이 필요하다. 샤워를 하고 나면 수건으로 보송보송하게 닦지 말고 저절로 마를 때까지 내버려 둔다. 샤워 가운을 입고 기다리는 것도 좋은 방법이다. 이 시간에 피부는 물기를 빨아들이고 탄력을 되찾는다.',null,null,to_date('20/04/14','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'차조기잎이 좋은 이유','hospital1','위장이 약해 설사를 자주할때는 차조기잎을 끓여마시면 좋다',null,null,to_date('20/04/15','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'양배추가 좋은 이유','hospital2','위염.위궤양에 양배추를 날것으로 보름정도 먹으면 효과가있다',null,null,to_date('20/07/01','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'적포도주가 좋은 이유','hospital1','적포도주는 물론 포도주스도 심장병예방에 효과가 있다',null,null,to_date('19/07/02','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'육류 먹는법','hospital3','육류는 냉장실.생선.조개류는 물에담가 해동을 시킨다',null,null,to_date('20/07/03','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'술이 안좋은 이유','hos1','술은 고환 기능저하를 초래해 남성호르몬 수치를 떨어뜨린다',null,null,to_date('20/07/04','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'고사리 먹는법','hospital1','고사리는 브라켄톡신이라는 발암물질때문에 반드시 삶아 먹어야한다',null,null,to_date('20/07/05','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'당근이 좋은 이유','hospital2','당근을 잘게 자르거나 으깨면 유익한 성분인 카로틴이 급속히 산화된다',null,null,to_date('20/07/06','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'밤 먹는법','hos1','밤은 속껍질과 과육에 탄닌 성분이 많기 때문에 속까지 굽지않는것이 좋다',null,null,to_date('20/07/07','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'인삼 먹는법','hospital1','인삼은 꿀에 재놓으면 일종의 독소성분이 발생하므로 좋지않다',null,null,to_date('20/07/10','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'파래가 좋은 이유','hos1','파래속에 함유된 메틸 메티오닌은 위.십이지장궤양을 막아주는 효과가있다',null,null,to_date('20/07/12','RR/MM/DD'),0);
Insert into WEB1.BOARD_HEALTH (BOARD_NO,BOARD_TITLE,HOSP_ID,BOARD_CONTENT,BOARD_ORIGINAL_FILENAME,BOARD_RENAMED_FILENAME,BOARD_DATE,BOARD_READCOUNT) values (SEQ_BOARD_NO.nextval,'갈치를 먹을 떄 주의사항','admin','갈치는 부스럼이나 습진등 피부염이 있을땐 먹지않는게 좋다',null,null,to_date('20/07/13','RR/MM/DD'),0);

--댓글/단 게시판 번호를 보고 insert할것
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'admin', '정말로 훌륭한 정보 군요!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'admin', '정말로 훌륭한 정보 군요!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'honggd', '밤에 눈이 침침햇는데 잘됫네요!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'turtle', '왜구놈 혼낼려면 건강을 챙겨야죠!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'joseon', '내가  바로 조선의 초대 국왕이니라!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'Faker', '롤하기전에 몸풀기에 딱좋겟네요!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'Faker', '롤드컵 우승을 위해!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'cheonghaejin', '내가바로 통일신라시대의 장수이니라!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'cheonghaejin', '이순신이 날 따를려면 이 상식을 다 외워야지!', 30, null, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 1, 'joseon', '짐은 참으로 뿌듯하구나!', 30, null, default);

--대댓글/단 댓글의 번호를 확인후 insert할것 / 병원 닉넴 정해지면 넣을것
insert into board_health_comment values(seq_board_health_comment.nextval, 2, 'admin', '감사합니다!', 30, 10, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 2, 'hos1', '건강하세요!', 30, 3, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 2, 'hos1', '훌륭한 왕이 되세요!', 30, 5, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 2, 'hos1', '바다에서도 힘내세요!', 30, 4, default);
insert into board_health_comment values(seq_board_health_comment.nextval, 2, 'Fater', '이제 롤의 신이 되는거에요!', 30, 6, default);

commit;

SELECT * FROM board_health_comment;